### ISSUE TITLE
[BUG] script.placeholder

### ISSUE THREAD

**Issue by djgragra** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#108]
**Describe the bug**  
I receive a notification "script.placeholder" missing  
How to resolve?

-== Watchman Report ==-
Service ID                     | State   | Location                                                     |
+--------------------------------+---------+--------------------------------------------------------------+
| script.placeholder             | missing | skyqSoggiorno.yaml:9,18,27,36,46,56,66,76,86,96,106,116,126, |
|                                |         | 136,146,156,166,176,186,196,206,216

**Comment by RogerSelwyn** [comment]
Following on, are you actually experiencing any issues using the generated switches? If not, I think you watchman report (which I assume is this https://community.home-assistant.io/t/watchman-keeps-track-of-missing-entities-and-services-in-your-config-files/390391) is reporting a non-issue as far as the correct functioning of the switches is concerned.

**Comment by RogerSelwyn** [comment]
Thanks I understand what is causing watchman to report this. It isn't an issue for you, but I will try to resolve anyway.

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.9.5
