### ISSUE TITLE
[Problem]

### ISSUE THREAD

**Issue by drako86** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#109]
**Describe the bug**  
Since installed, the decoder behaves strangely, periodically loses the connection and the decoder is unresponsive. You have to take off the power and put it back on.

**Component versions**  
1. My version : 2.9.6

**Your configuration**  
by UI

**Extra**
Before writing here, I had the decoder changed by Sky, but the problem persists

**Comment by RogerSelwyn** [comment]
Unfortunately some people occasionally suffer from this. My only suggestion is to ensure that Get Live Record Status is False (the default) which reduces the number of calls on the port that seems to cause the problem. 

My apologies but I’m afraid there is no fix for it, for most people it is fine, but occasionally someone has a problem.

**Comment by drako86** [comment]
Thank you, I will try to disable the check and check
