### ISSUE TITLE
[BUG] W0020DA - No Control URL, SOAP call not made: sky-q.home.lan : GetTransportInfo

### ISSUE THREAD

**Issue by richard-scott** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#111]
**Describe the bug** 
I get Disk Usage from this Integration, but I can't control my Sky Box as I get this error:

![Screenshot 2022-07-29 at 20 54 07](https://user-images.githubusercontent.com/5149834/181834198-2d656e1c-f208-4e19-9d81-5bf3eaa6d3c2.png)

**To Reproduce**  
1. Add the Integration to HA, and setup your Hostname.

**Expected behavior**  
I expected a media player to start working

**Component versions**  
1. What version of SkyQ component are you using? v2.9.6

**Your configuration**  
How have you setup your devices, by UI or YAML?

Setup by UI with no other options changed from default.

**Additional context**  
It seems that the Integration works fine when using IP, but not by FQDN of a locally generated hostname e.g sky-q.home.lan, where home.lan is added to DHCP leases on my network.

Oh, and Storage is now showing as Unavailable!

**Comment by RogerSelwyn** [comment]
Please can you provide the output from this query, obviously with the right IP.

http://192.168.1.122:9006/as/system/information

**Comment by RogerSelwyn** [comment]
Just to add, if it works correctly via ip, then validate that name resolution works fine from you home assistant terminal session.

**Comment by richard-scott** [comment]
> Please can you provide the output from this query, obviously with the right IP.
> 
> http://192.168.1.122:9006/as/system/information

{
"ASVersion": "Q190.000.16.00-AS_25.2.1",
"CAType": "VIDEOGUARD",
"DRMActivationStatus": true,
"IPAddress": "192.168.0.62",
"MACAddress": "D4:DA:CD:F0:72:E7",
"activeStandby": false,
"airplayID": "Sky Q 1TB Box6803",
"btID": "Sky Q 1TB Box6803",
"cable": false,
"deviceID": "redacted",
"deviceType": "GATEWAYSTB",
"gateway": true,
"gatewayIPAddress": "not MR",
"hardwareModel": "ES340A-d8UKIE",
"hardwareName": "Titan",
"hdrCapable": true,
"householdToken": "redacted",
"localIRDatabase": true,
"manufacturer": "Sky",
"meshEnabled": true,
"modelNumber": "Q190.000.16.00L (5gsyc00)",
"networkVersion": "2.00",
"numDTTTuners": 0,
"pipCapable": true,
"purchasebalance": "0.01",
"purchaselimit": "100.01",
"receiverID": "A 33824175026D74F8",
"serialNumber": "0635056803 6",
"systemUptime": 382440,
"uhdCapable": true,
"versionNumber": "32B214",
"viewingCardNumber": "884511528",
"wakeReason": "POWERON"
}

**Comment by richard-scott** [comment]
It works with IP for both Control and Storage, but when using a FQDN hostname, only Storage shows up.

**Comment by RogerSelwyn** [comment]
Ok, I’ll see if I can figure out if anything is going on

**Comment by RogerSelwyn** [comment]
Look's like the Sky Q box doesn't support being addressed using hostname for call on that port. Nope, I don't know why. This is the call it is doing in curl form.

`curl --location --request GET 'http://skyq.local:49153/description1.xml' --header 'User-Agent: SKYPLUS_skyplus'`

But I believe I can retrieve the IP address from the box from a previous call, and then use that instead of hostname. This should then still give you name resolution via your router.

**Comment by RogerSelwyn** [comment]
Please try setting pyskyqremote to 0.3.14 in the sky manifest.json.

```
  "requirements": [
    "pyskyqremote==0.3.14"
  ],
```

**Comment by RogerSelwyn** [comment]
Closed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.9.7
