### ISSUE TITLE
Change quality of episode thumbnail

### ISSUE THREAD

**Issue by gooberstank** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#113]
It would be great to request higher-quality episode thumbnail images.
The current URL has 456 hardcoded in which only requests an image of 456px wide.

e.g.

**https://imageservice.sky.com/pd-image/1c54548b-4afa-4d8a-aab4-19e7201c26bb/16-9/456?territory=GB&provider=SKY&proposition=SKYQ**

The Sky URL supports swapping out 456 with any number. By eye it seems that using 1080 gives the maximum quality available, everything above it is scaled (I could be wrong on that).

Being able to choose to get thumbnails in 1080px or above would look much sharper on my HA install on a large tablet.

**Comment by RogerSelwyn** [comment]
Completed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.9.8
