### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Welahninja** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#115]
Is there a way of adding apps to the list eg Netflix

**Comment by RogerSelwyn** [comment]
To which list? Please expand on what you are trying to achieve.

**Comment by Welahninja** [comment]
You have the list of TV channels you can select is there something similar where I can select Netflix or any other app on sky Q

**Comment by RogerSelwyn** [comment]
Assuming you are using a ui based installed you need to add it to the custom sources as described here - https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/configuration_ui.html

Using the buttons available here - https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/buttons.html

An example using yaml based install is here - https://community.home-assistant.io/t/custom-component-skyq-media-player/140306/322

Unfortunately there is no simple list, you have to put the buttons you would need to press on your remote to get to the app on your SkyQ box.
