### ISSUE TITLE
Failed to connect to host.

### ISSUE THREAD

**Issue by mattiaoui** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#117]
I have problem to connect my skyq to hassio os.
My hassio server are in different vlan between skyq.
Gateway are firewall,frok hassio i ping or download index.html with curl.
How protocol use hassio to connect to SkyQ?

Thanks
Mattia

**Comment by RogerSelwyn** [comment]
You will need to enable port 9006, 49153 and 49160.
