### ISSUE TITLE
[Feature Request] Replace Switch to Button

### ISSUE THREAD

**Issue by bluenazgul** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#118]
Right now this Integration is able to use Switches to Change Channels or do other Things on the Sky Q Receiver. 

Switches are permanent until you turn them off again. 

Als the functions this Switches do are only "send a Single Signal or an array of Signals once a time, why dont change the to Buttons? 

I think Buttons are much better for this Case.

**Comment by RogerSelwyn** [comment]
The switches that are generated should automatically turn off. If that isn't the case, then there is a bug.
