### ISSUE TITLE
Broken SwitchGeneration for Sky Sports Football HD channel

### ISSUE THREAD

**Issue by andypburke** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#119]
Thanks for this component which I find excellent.  However, today I discovered an issue where the automatically generated switches include Sky Sports Football HD but has introduced quotes in the title.  This prevents HomeAssistant from restarting or using alias.   I suspect this may be a bug in the EPG.   Below is the code snippet from the generated switches yaml.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/4771045/193015460-b661a864-86ea-47f6-a265-909944d13994.png">

**Component versions**  
1. I am using 1.27.2 version

Devices have been setup through the UI to generate the generated switches YAML file

**Configuration File** 

media_player:
 - platform:  skyq
   name: SkyQ Extension
   host: 192.168.86.74
   sources:
      SkyOne: '1,0,6'
      SkyNews: '5,0,1'
   generate_switches_for_channels: true
   room: Extension

switch:
- platform: template
  switches: !include  skyqExtension.yaml

**Logs**

2022-09-29 11:58:23.129 ERROR (SyncWorker_6) [homeassistant.util.yaml.loader] while parsing a block mapping
  in "/config/skyqExtension.yaml", line 394, column 7
expected <block end>, but found '<scalar>'
  in "/config/skyqExtension.yaml", line 395, column 31
2022-09-29 11:58:23.196 ERROR (MainThread) [homeassistant.components.homeassistant] The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/skyqExtension.yaml", line 394, column 7
expected <block end>, but found '<scalar>'
  in "/config/skyqExtension.yaml", line 395, column 31
2022-09-29 11:58:23.219 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140179203173888] The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/skyqExtension.yaml", line 394, column 7
expected <block end>, but found '<scalar>'
  in "/config/skyqExtension.yaml", line 395, column 31
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 746, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 174, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/skyqExtension.yaml", line 394, column 7
expected <block end>, but found '<scalar>'
  in "/config/skyqExtension.yaml", line 395, column 31

**Comment by RogerSelwyn** [comment]
You have stated you are using version 1.27.2, the earliest version I have created is version 2.0 and the current version is 2.9.10. Can you check the version, because the output does look like it could have been generated by 2.9.8 or greater.

That said, I just generated using that channel, and I get the below which should work fine.

```
    skyq_skyspfballhddefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'SkySp Fball HD in the Default Room'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q_mini
            source: 'SkySp F''ball HD'
        - delay:
            seconds: 10
      turn_off:
        stop:
```

But to add, with the sources you have specified in your config.yaml, you wouldn't get the Football channel, you'd only get Sky One and Sky News

**Comment by andypburke** [comment]
Yes it has generated it differently to yourself

      friendly_name 'SkySp F'ball HD in the Extension'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q
            source: 'SkySp F''ball HD'
        - delay:
            seconds: 10
      turn_off:
        stop:

**Comment by RogerSelwyn** [comment]
Try configuring through the UI rather than YAML. Or if doing via YAML, give me tour actual config, not your cut down one.

**Comment by andypburke** [comment]
Thanks.  That is configured from the UI.  This is just the snapshot from the config file.

**Comment by RogerSelwyn** [comment]
Do you have diagnostics enabled on your install? If not you can add it by adding `diagnostics` to your config.yaml.

Then can you download the diagnostics report. This can be done by going to the device in the Integrations pane, and clicking on the three dots at the bottom right of the Device Info panel. Feel free to blank out any item you may want hidden such as IP address and serial number. Then can you upload here.

Thanks

**Comment by RogerSelwyn** [comment]
Have you got an alias file?

**Comment by andypburke** [comment]
Thanks.  I did try to utilise the skyqswitchalias.yaml file but it didn't map the alias appropriately.   However, for some reason today it is working and I don't get the error when I need to restart HA.  Very odd as the friendly name still references the ' in the name.

**Comment by RogerSelwyn** [comment]
The reason I asked about the alias file is that the values in there were not checked for an apostrophe, so that would cause the problem. I've added a code change to rectify that. 

Bear in mind that any switch yaml file generated will only get used at the next reboot, so if there is an apostrophe in there it would be worth doing another reboot to validate there is no problem. You can check by looking in the developer tab at what the entities actually look like.

I'm interested that you say the aliases didn't map, but I'm guessing you don't want to pursue that if you have a working environment.

**Comment by andypburke** [comment]
Thanks. Yes it is odd that the friendly name with the apostrophe hadn't changed but now I can map the alias when I couldn't before.  No worries though as it is all working now.

**Comment by RogerSelwyn** [comment]
Fixed to correctly handle aliases - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.9.11
