### ISSUE TITLE
Ability to identify whether an app is actually playing

### ISSUE THREAD

**Issue by asknoone** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#120]
When you go into an app, e.g. Netflix it shows attribute information about it being in the app but the state is "playing" even though there isn't anything playing as such, it's just on the "home" screen of the app.

Ideally there would be a way to identify if an app is on the Home screen or is in a film/movie/episode. And the state would show whether it is actually paused or playing.

The reason I want to know this is because I have automations which pause the TV for me when no presence is detected in the lounge and then plays it again when presence is detected.

However, if I am on the home screen of Netflix, haven't chosen a movie to watch yet and go and grab a drink then it "pauses" for me because it thinks something is playing (state shows as "playing"), which actually then ends up playing the selected item from the home screen.

I'm guessing that this information from the app is not presented to the Sky box and therefore not in the API? But I thought I'd ask just in case!

**Comment by RogerSelwyn** [comment]
I'm afraid this isn't possible. The most the sky box knows is that Netflix is open. It would need to be able to a Netflix api (and equivalent for all other services). This is well outside the scope of this integration. 

Sorry.

**Comment by asknoone** [comment]
Wow, had I even pressed send before you responded?! :-)

I thought that would be the case, shame. Thanks for the reply!

**Comment by RogerSelwyn** [comment]
> Wow, had I even pressed send before you responded?! :-)
> 
> I thought that would be the case, shame. Thanks for the reply!

Just watching TV, so easy to respond on  this one. I like new ideas, and I’ve thought about this one often, but can’t achieve it.
