### ISSUE TITLE
[Feature Request] Open Netflix

### ISSUE THREAD

**Issue by McFarTech** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#130]
Hello. 

Apologies if this is covered somewhere and i have missed it. I was also not sure where to log this type of request. 

Is it possible or could i request the ability to Open Netflix from the Sky Q Media player. I see i can create a source for any channels i want to use but it would be epic to be able to select Netflix as well. Not even sure if this is possible or not. 

Thanks in advance

**Comment by RogerSelwyn** [comment]
You need to create a custom source as defined [here](https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/configuration_ui.htm), using the correct button sequence that would open the Netflix app as if you were using the remote. There is no 'open app' option in the api, just the buttons as you have on your remote.

**Comment by McFarTech** [comment]
Thank you. Can i just double check that link with you as i get a page 404

**Comment by McFarTech** [comment]
If its this page? https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/configuration_ui.html

I see you say about sources. Do you have any other example of how you would se this up? something real world

**Comment by RogerSelwyn** [comment]
Yes, there is one at the bottom of the page, replace BBC1HD with Netflix and '1,1,5' with the appropriate buttons to get to Netflix (sorry I don't know the correct sequence'.

Useable buttons are shown [here](https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/buttons.html)

**Comment by RogerSelwyn** [comment]
Examples of Netflix here, but done via YAML. Just copy the button sequence into the json structure in the example.

https://community.home-assistant.io/t/custom-component-skyq-media-player/140306/323

It is for an Italian box, so may be different on a UK box.

**Comment by McFarTech** [comment]
Thank you. all that information was really useful and i now have this setup so that i can select Netflix as a source. 

My next thing is to try and sort out is how to use that as part of a automation. for Example Alexa , Netflix time and that changes Sky Q to Netflix and then dimms my lights etc.

**Comment by McFarTech** [comment]
Actually. All sorted via NodeRed.  I really appreciate your help this morning. Thank you
