### ISSUE TITLE
Schedule and Storage sensors

### ISSUE THREAD

**Issue by bradlsi01** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#131]
I'm happy to accept I'm an HA dumb newbie, but I'm missing the magic beans needed to re-enable the storage sensor.  I know it used to work, but since a recent release it has stopped working.  How do I turn it back on?

I'm also really confused about how the schedule sensor works and is enabled.  The documentation isn't a huge amount of help.

Any pointers would be really appreciated.

**Comment by RogerSelwyn** [comment]
You can enable them via the settings, devices and services dialogue. I'm afraid I made the assumption in the documentation that users would have an understanding of entities and how to enable/disable them. No problem being a newbie 😀
![IMG_0336](https://user-images.githubusercontent.com/7115783/206927556-ee56537c-0857-41d4-acff-03a3764061ed.png)

**Comment by bradlsi01** [comment]
Hi Roger,

Thanks for the quick response, but I'm not THAT much of a newbie :-)  I suspect I have messed up in a much more creative way, as I'm not seeing those entities at all
![image](https://user-images.githubusercontent.com/99152205/206932382-5ed5e629-5e7a-4986-a176-b27c42c654ae.png)

**Comment by RogerSelwyn** [comment]
Sorry, not sure how you've done that. I'd delete and re-add it. Note the sensors don't get created for SkyQ mini box (just in case that is what you are adding).

**Comment by nightmare1111** [comment]
Im seeing the same, the entity stopped working with a recent ha december update, my storage entity said it was no longer providing the i formation. I deleted the storage entity but i cant see how to get it back.

**Comment by RogerSelwyn** [comment]
I’ll investigate some more, but have you tried deleting and re-adding? Also checking it isn’t just disabled?

**Comment by RogerSelwyn** [comment]
@bradlsi01 , @nightmare1111  I think I know what it might be. Can you confirm if you have diagnostics enabled in your HA config?

**Comment by RogerSelwyn** [comment]
If that isn't the case, please run the following against the ip of your box, and report back. Block out any sensitive info such as token, ids and Mac.

**Comment by bradlsi01** [comment]
HI Roger, Merry Christmas!

I should have said, I got then back by removing the integration entirely and installing an earlier version.  That seems to have stabilised something, as the later release have continued to work.  

> @bradlsi01 , @nightmare1111 I think I know what it might be. Can you confirm if you have diagnostics enabled in your HA config?

I don't think I do, but I will do if you tell me what to turn on :-)

**Comment by bradlsi01** [comment]
> If that isn't the case, please run the following

Run whatnow?

**Comment by RogerSelwyn** [comment]
> I should have said, I got then back by removing the integration entirely and installing an earlier version. That seems to have stabilised something, as the later release have continued to work.

So are you now on the latest release?

**Comment by RogerSelwyn** [comment]
> Run whatnow?

192.168.1.122:9006/as/system/information

**Comment by bradlsi01** [comment]
> So are you now on the latest release?

Yes, v2.10.6a2

**Comment by RogerSelwyn** [comment]
Strange that going to an older version fixed anything.

**Comment by bradlsi01** [comment]
> 192.168.1.122:9006/as/system/information
{
   "ASVersion" : "Q210.000.06.03-AS_27.4.0",
   "CAType" : "VIDEOGUARD",
   "DRMActivationStatus" : true,
   "IPAddress" : "192.168.xxx",
   "MACAddress" : "xxxxx",
   "activeStandby" : false,
   "airplayID" : "Main Sky Q",
   "btID" : "Sky Q 2TB Box8763",
   "cable" : false,
   "deviceID" : "xxxxx",
   "deviceType" : "GATEWAYSTB",
   "gateway" : true,
   "gatewayIPAddress" : "not MR",
   "hardwareModel" : "ES340d9UKIE",
   "hardwareName" : "Titan",
   "hdrCapable" : true,
   "householdToken" : "xxxx",
   "localIRDatabase" : true,
   "manufacturer" : "Sky",
   "meshEnabled" : true,
   "modelNumber" : "Q210.000.06.03L (5k4107v)",
   "networkVersion" : "2.00",
   "numDTTTuners" : 0,
   "pipCapable" : true,
   "purchasebalance" : "0.01",
   "purchaselimit" : "100.01",
   "receiverID" : "9 1EBE59E8026D74F8",
   "serialNumber" : "xxxxx",
   "systemUptime" : 54016,
   "uhdCapable" : true,
   "versionNumber" : "32B206",
   "viewingCardNumber" : "XXXX",
   "wakeReason" : "ECO"
}

**Comment by RogerSelwyn** [comment]
That's what I'd expect to see, it only creates the sensors for GATEWAYSTB, and now creates as diagnostic entities which is why I asked about diagnostics. I'd need to have someone who currently has the problem to try and see what is causing it.

Thanks for your help.

**Comment by nightmare1111** [comment]
I am still seeing the issue with no storage sensor

`Logger: homeassistant.components.sensor
Source: custom_components/skyq/utils.py:120
Integration: Sensor (documentation, issues)
First occurred: 5:22:45 PM (3 occurrences)
Last logged: 5:47:23 PM

Error while setting up skyq platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/skyq/sensor.py", line 65, in async_setup_entry
    sensors = [SkyQUsedStorage(hass, remote, config)]
  File "/config/custom_components/skyq/sensor.py", line 83, in __init__
    attributes = read_state(
  File "/config/custom_components/skyq/utils.py", line 120, in read_state
    if sensor[Platform.SENSOR] == sensor_type:
KeyError: <Platform.SENSOR: 'sensor'>
`

**Comment by RogerSelwyn** [comment]
@nightmare1111  Can you post the contents of `.storage/skyq.restore_state` to help my debugging. Then you can delete/rename that file and you should be sorted.

**Comment by nightmare1111** [comment]
> thanks where would i find .storage/skyq.restore_state

**Comment by RogerSelwyn** [comment]
In your configuration directory, it is a hidden folder. Assuming you have file editor addon installed and can’t see it, go to configuration of the addon and remove .storage as an ignored folder.

**Comment by nightmare1111** [comment]
> @nightmare1111 Can you post the contents of `.storage/skyq.restore_state` to help my debugging. Then you can delete/rename that file and you should be sorted.

`    skyq_pausedefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'pause in the Default Room'
      turn_on:
        - service: media_player.media_pause
          data:
            entity_id: media_player.sky_q
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_playdefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'play in the Default Room'
      turn_on:
        - service: media_player.media_play
          data:
            entity_id: media_player.sky_q
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_ffdefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'fastforward in the Default Room'
      turn_on:
        - service: media_player.media_next_track
          data:
            entity_id: media_player.sky_q
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_rwdefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'rewind in the Default Room'
      turn_on:
        - service: media_player.media_previous_track
          data:
            entity_id: media_player.sky_q
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_bbconenihddefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'BBC One NI HD in the Default Room'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q
            source: 'BBC One NI HD'
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_utvhddefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'UTV HD in the Default Room'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q
            source: 'UTV HD'
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_skyatlanticdefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'Sky Atlantic in the Default Room'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q
            source: 'Sky Atlantic'
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_davedefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'Dave in the Default Room'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q
            source: 'Dave'
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_itv4defaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'ITV4 in the Default Room'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q
            source: 'ITV4'
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_discoverydefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'Discovery in the Default Room'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q
            source: 'Discovery'
        - delay:
            seconds: 10
      turn_off:
        stop:
    skyq_natgeodefaultroom:
      value_template: '{{"off"}}'
      friendly_name: 'Nat Geo in the Default Room'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.sky_q
            source: 'Nat Geo'
        - delay:
            seconds: 10
      turn_off:
        stop:
`

**Comment by nightmare1111** [comment]
@RogerSelwyn thanks for your help that has solved it.

**Comment by RogerSelwyn** [comment]
Ok, I’ll do a fix for others updating tomorrow.

**Comment by RogerSelwyn** [comment]
Closed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.10.8
