### ISSUE TITLE
Switch name contain "in the room name" - Trying to use it with Alexa

### ISSUE THREAD

**Issue by SuperMitic** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#133]
I've managed to setup this integration in HASS and i am trying to use it with Alexa. I've enabled the option to generate the switches. But the friendly_name of every channel is "channel name + in the + room name", so i have to ask alexa, "channel name + in the + room name". Is there a way to just say the channel name. I even tried using the aliases to change channel name, but it doesn't work.

Thanks for your work!

**Comment by RogerSelwyn** [comment]
Just chewing over this one, what would you do for play/pause/etc, say it without the room name?
