### ISSUE TITLE
Restored from backup, "failed to connect to host"

### ISSUE THREAD

**Issue by gumbald** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#134]
Hello! I'm in the process of migrating my HA install from Pi to VM running in VirtualBox and it seems to have an issue connecting to Sky Q box: "failed to connect to host". I've got both instances running, so can compare anything as needed. Q box doesn't seem to respond to pings, but hasn't changed IP address (as original install still working). VM is bridged (so appears on same subnet as Q box and Pi). Anything else that the VM could be doing differently? Or any way I can debug the connectivity path?

**Comment by RogerSelwyn** [comment]
That looks like a network problem. SkyQ box does not respond to ping. Try the below command from a terminal session on you HA server. When that works, the integration should work.

`curl http://192.168.1.122:9006/as/system/information`

**Comment by gumbald** [comment]
That command did succeed - tried to add it again and it worked! curl command not working from another box though (nothing to do with HA), gives me something to investigate on my network... Thanks for the help!
