### ISSUE TITLE
How to replicate screenshot?

### ISSUE THREAD

**Issue by nikoloiz** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#140]
Hi, sorry if this is a bit of a dumb question - I’m quite new to HA. I was wondering how to access the ‘library’ section for the Sky Box (like the fourth screenshot in the README) I assumed it would appear as a playback source in the Media tab of the Sidebar. 

Thanks, nikoloiz

**Comment by RogerSelwyn** [comment]
Click on the icon, usually at top left of Lovelace card, then there should be a browse media link

**Comment by RogerSelwyn** [comment]
Or at least that works in mini media player, no idea in the standard Lovelace card
