### ISSUE TITLE
[BUG] Error on startup for schedule sensor

### ISSUE THREAD

**Issue by ancientm74** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#141]
Hi, since I updated to the latest version, this error appears every time I restart, even if the integration works perfectly, can anyone help me? Thank you
![errore](https://user-images.githubusercontent.com/63248398/215278234-7cab1b43-e508-4ab2-a37e-bd52ded014d5.jpg)

**Comment by RogerSelwyn** [comment]
Should be fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.10.11

**Comment by ancientm74** [comment]
Hi and thanks but still giving the same error
![Immagine 2023-01-30 081814](https://user-images.githubusercontent.com/63248398/215412167-41da3411-f8ae-4b18-be2e-a7f2e5a9f1fa.jpg)

**Comment by RogerSelwyn** [comment]
My apologies this will fix the problem - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.10.12
