### ISSUE TITLE
Sky Glass and Puck support

### ISSUE THREAD

**Issue by gpchampion** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#142]
Not a problem as such Roger, and thanks for the ongoing works on Sky Q for HA.

More of a feature request, which I know has been mentioned from time to time.

It seems that Sky is going towards streaming devices (Glass/Pucks etc) and they are now actively marketing them in favour of Sky Q. 
Is it now possible to include such devices, or is the information unavailable, so just not possible to incorporate into NR/HA etc?

Your views/statement would be most welcome.

**Comment by RogerSelwyn** [comment]
I don't have one of the internet only devices to try against, and from what I hear Sky have been removing some of the apis the integration uses, and we've never been able to find a critical one that we absolutely need. For some reason Sky don't seem to want to make their devices more accessible, which seems to me to be likely to reduce their uptake in the future.

Sorry, but I don't see it happening. I would if I could, but I can't.

**Comment by binc0** [comment]
I tested with [CLI](https://github.com/dalhundal/sky-remote-cli) on Sky Glass trough port 49160 and commands work fine but as I know they removed port 9006 infos.

**Comment by mrdarrengriffin** [comment]
Argghh. I didn't realise Sky had done this. I just took out a new contract with them as I'm moving home and didn't want a satellite dish anymore. I wonder if their engineering team just built the puck differently or saw that people were leveraging the unofficial API like this?

I haven't got my Stream Puck yet but I'm curious to find out if there's another way. Maybe the MySky app has some insights and has some telemetry in there. It's probably all encrypted but might be worth sniffing the network to find out. 

Let's not give up hope! I love this integration too much to let some corporate giant take it away!

**Comment by RogerSelwyn** [comment]
I'm not aware of any app on phone or pc that supports Sky Glass or Stream. They seem completely isolated. I don't understand the motivation from Sky to limit their user base.

**Comment by mrdarrengriffin** [comment]
Yeah maybe not after doing some research. 

To be honest, I'm reading that the Stream service is much worse than Sky Q anyway. I might cancel altogether and try something else.
