### ISSUE TITLE
Change IP Address

### ISSUE THREAD

**Issue by djgragra** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#143]
I have to change the Sky Q.
What is the problem if I do it?
Do I have to redo the whole configuration?

**Comment by RogerSelwyn** [comment]
If you ip has changed you will need to delete and re add the integration. As I’ve suggested either set a static ip on your router or use the name that your sky box is known as on your router so you don’t need to reconfigure in the future.
