### ISSUE TITLE
[BUG] Media Browser Issue

### ISSUE THREAD

**Issue by Bobby5291** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#148]
Media browsing 
I downloaded the update to stop the media browsing error as I was getting that error. Know when I press browse media it shows loading like the blue ring circling. It will stay like that for around 3 or 4 minutes. After it says media browsing error. 

I am in the UK

If you want pictures I can send them

**Comment by RogerSelwyn** [comment]
Please post picture and any errors from the system log.

**Comment by RogerSelwyn** [comment]
Please also provide info on your configuration, I.e. what channels you have set against the sources lists. Aha ensure you have cleared your browser cache.

**Comment by Bobby5291** [comment]
I went to the shops and I have now come back and the problem has fixed. The only thing to add is that it takes some time for all the media to load but I think that is my wifi thanks for your help and quick reply

**Comment by RogerSelwyn** [comment]
If you have a lot of sources then it will take a long time. It pulls back a lot of data especially if you have more than 20 channels configured in your sources. By default the integration caches 20 channels, if you have more than that it will be pulling the data every time. 

See these two links:
https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/configuration_ui.html
https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/media_browser.html
