### ISSUE TITLE
Stream movies from NAS to Sky Q via home assistant

### ISSUE THREAD

**Issue by leeandy1** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#150]
I am unsure whether the Sky Q box supports this but now we have network storage available in Home Assistant it would be great to stream from a NAS drive to Sky Q.

**Comment by RogerSelwyn** [comment]
Sorry, no. The Sky Q integration deals with Sky Q boxes only, and does no streaming. I do. Or believe you might be able to AirPlay to a sky box (not sure), in which case you'd need to find whether there is an airplay integration that could support playing from NAS.
