### ISSUE TITLE
SkyQ - No devices or entities

### ISSUE THREAD

**Issue by detxm80** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#152]
Hi, it's a few version that my integration stop working....
If i put my skyq ip integration says "No devices or entities"

i've the latest version by hacs and HA

i tried to delete it and reinstall it without success

**Comment by RogerSelwyn** [comment]
Please can you properly fill in the bug report with clear steps to follow and details of your configuration. 

From what you have written I have no idea where you are putting the ip address, where you are getting the message from or what errors are shown in the log.

**Comment by detxm80** [comment]
![IMG_7037](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/32907141/d95d28dd-80d2-49bc-93d1-099073b37f8a)
![IMG_7038](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/32907141/b43eedaa-38f8-4e14-94cf-93d4ebb07cb0)
![IMG_7039](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/32907141/a1e6af08-5714-4fe4-bbe2-1d3e28ca71cc)

**Comment by RogerSelwyn** [comment]
Please run this command against your box:

http://192.168.1.122:9006/as/system/information

**Comment by detxm80** [comment]
> Please run this command against your box:
> 
> http://192.168.1.122:9006/as/system/information

![IMG_7040](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/32907141/9bf4ebeb-003a-40dd-a2e4-aa33fff926fe)

**Comment by detxm80** [comment]
> Please run this command against your box:
> 
> http://192.168.1.122:9006/as/system/

![IMG_7040](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/32907141/7d329aa5-db66-443b-9733-b11776ebd905)

**Comment by RogerSelwyn** [comment]
Please don't do screenshots, just paste the content using the <> in the GitHub toolbar, it will make it much easier to read.

- Are there any errors in the log?
- What happens when you delete and re-add the integration?
- What is the last version where it worked?
- If you return to that version, does it work again?

**Comment by warez1975** [comment]
Hi, I've the same problem. Here is my output from: `http://192.168.1.224:9006/as/system/`

Installed version: V2.11.2

`{
   "developerMessage" : "An URL which did not translate into an AS call was received. The URL was GET 9006/as/system/",
   "errorCode" : 101,
   "userMessage" : "Invalid URL"
}`

I've the same problem also if I delete and re-add the integration (reboot system anche clear browser cache)

HA and HACS are update to the last version.

Thank you for your work and any helps are appreciated.

**Comment by RogerSelwyn** [comment]
Should have been this url, sorry.

http://192.168.1.122:9006/as/system/information

**Comment by warez1975** [comment]
Sorry, here is the correct output:

`{
   "ASVersion" : "Q220.000.23.00-AS_28.7.0",
   "CAType" : "VIDEOGUARD",
   "DRMActivationStatus" : true,
   "IPAddress" : "192.168.1.224",
   "MACAddress" : "0C:08:B4:8A:46:5A",
   "activeStandby" : false,
   "airplayID" : "Sky1592",
   "btID" : "Sky1592",
   "cable" : false,
   "chipID" : "263 243 0773 0",
   "deviceID" : "6763A30673751592",
   "deviceType" : "GATEWAYSTB",
   "gateway" : true,
   "gatewayIPAddress" : "not MR",
   "hardwareModel" : "ESi-160",
   "hardwareName" : "Amidala",
   "hdrCapable" : true,
   "householdToken" : "000002BE00000054020C2E4A5041E48BF92411FE3211E2B10300D4AA200F3B88D19BD859D8B6000000000000001E000000000000001649543030303030303030303030303032323630303332F02679CD624599736B623172CE1C06DB",
   "localIRDatabase" : true,
   "manufacturer" : "HUMAX",
   "meshEnabled" : false,
   "modelNumber" : "Q220.000.23.00L (5lrke0s)",
   "networkVersion" : "2.00",
   "numDTTTuners" : 1,
   "pipCapable" : true,
   "purchasebalance" : "0.01",
   "purchaselimit" : "30.01",
   "receiverID" : "7 1CE7B4B501989CD1",
   "serialNumber" : "0673751592 3",
   "subscriberID" : "11106323",
   "systemUptime" : 41016,
   "uhdCapable" : true,
   "versionNumber" : "6763A3",
   "viewingCardNumber" : "300686862",
   "wakeReason" : "ECO"
}`

Thanks for your time!

**Comment by warez1975** [comment]
Sorry, here is the correct output.

`{
   "ASVersion" : "Q220.000.23.00-AS_28.7.0",
   "CAType" : "VIDEOGUARD",
   "DRMActivationStatus" : true,
   "IPAddress" : "192.168.1.224",
   "MACAddress" : "0C:08:B4:8A:46:5A",
   "activeStandby" : false,
   "airplayID" : "Sky1592",
   "btID" : "Sky1592",
   "cable" : false,
   "chipID" : "263 243 0773 0",
   "deviceID" : "6763A30673751592",
   "deviceType" : "GATEWAYSTB",
   "gateway" : true,
   "gatewayIPAddress" : "not MR",
   "hardwareModel" : "ESi-160",
   "hardwareName" : "Amidala",
   "hdrCapable" : true,
   "householdToken" : "000002BE00000054020C2E4A5041E48BF92411FE3211E2B10300D4AA200F3B88D19BD859D8B6000000000000001E000000000000001649543030303030303030303030303032323630303332F02679CD624599736B623172CE1C06DB",
   "localIRDatabase" : true,
   "manufacturer" : "HUMAX",
   "meshEnabled" : false,
   "modelNumber" : "Q220.000.23.00L (5lrke0s)",
   "networkVersion" : "2.00",
   "numDTTTuners" : 1,
   "pipCapable" : true,
   "purchasebalance" : "0.01",
   "purchaselimit" : "30.01",
   "receiverID" : "7 1CE7B4B501989CD1",
   "serialNumber" : "0673751592 3",
   "subscriberID" : "11106323",
   "systemUptime" : 41016,
   "uhdCapable" : true,
   "versionNumber" : "6763A3",
   "viewingCardNumber" : "300686862",
   "wakeReason" : "ECO"
}`

thank you for your time!

**Comment by RogerSelwyn** [comment]
- Are there any errors in the log?
- What happens when you delete and re-add the integration?
- What is the last version where it worked?
- If you return to that version, does it work again?

**Comment by warez1975** [comment]
> * Are there any errors in the log?

From HA log:

`Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/skyq/__init__.py", line 158, in _check_for_storage_contents
    file_content = json.load(infile)
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/skyq/__init__.py", line 64, in async_setup_entry
    _check_for_storage_contents(hass)
  File "/home/homeassistant/.homeassistant/custom_components/skyq/__init__.py", line 164, in _check_for_storage_contents
    except [json.decoder.JSONDecodeError, UnicodeDecodeError]:
TypeError: catching classes that do not inherit from BaseException is not allowed`

> * What happens when you delete and re-add the integration?

I have the same problem

> * What is the last version where it worked?

I try re-add (from HACS) integration from V2.10.13 to the latest and I have the same problem

Thanks for your time!!!

**Comment by RogerSelwyn** [comment]
Could you provide me a copy of the contents of `.storage/skyq.restore_state`, so I can simulate the error.

**Comment by RogerSelwyn** [comment]
Also try changing square brackets `[]` to round brackets `()` in line 164 of __init__.py.

**Comment by warez1975** [comment]
> Could you provide me a copy of the contents of `.storage/skyq.restore_state`, so I can simulate the error.

I try to open the file with VS Code but I see a blanc file... in the file info seem that this is a "zero byte" file

Thank you

**Comment by detxm80** [comment]
Same thing for me, i don’t have this file into custom_components/skyq/

**Comment by RogerSelwyn** [comment]
> Also try changing square brackets `[]` to round brackets `()` in line 164 of `__init__.py`.

This will fix the problem.

I know you were responding to the initial post, but always always provide all the information requested. With the right info, I was able to identify the issue in 5 minutes. Without it, I have no idea. Which is why I have changed the bug reporting template that forces people to provide everything.

> Same thing for me, i don’t have this file into custom_components/skyq/

It is in the root of your config. I should have more correctly put `/.storage/skyq.restore_state`

**Comment by RogerSelwyn** [comment]
To give an idea the error you provided gave the exact line the problem was on.

**Comment by RogerSelwyn** [comment]
Should be fixed with v2.11.3 - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.11.3

**Comment by detxm80** [comment]
Thanks!!!

**Comment by warez1975** [comment]
thank you for your time

**Comment by warez1975** [comment]
> Should be fixed with v2.11.3 - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.11.3

work like a charm... thank you for your work!!!!
