### ISSUE TITLE
[Feature Request] Control SkyQ box via automations

### ISSUE THREAD

**Issue by mogusbi-motech** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#154]
**Is your feature request related to a problem? Please describe.**  
I am unable to control my SkyQ box via an automation.

**Describe the solution you'd like**  
I would like to be able to automate certain actions such as turning my box on and off

**Describe alternatives you've considered**  
I have tried to add an action but no options are available

![image](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/53015240/ecb94770-835c-49e7-a3b8-5af9153842f1)

**Additional context**  
See above

**Comment by RogerSelwyn** [comment]
This is perfectly possible with the current media_player.turn_on/off services. I don’t use HA default automations (I use Node Red), but I know it works from the services view in the Developer Tools dialogue, so I’m 100% sure you can make the same service call from an HA automation.

**Comment by RogerSelwyn** [comment]
If you go to Services in Developer Tools, and go to YAML mode it will full example data for you.

**Comment by RogerSelwyn** [comment]
You need to do a service call action rather than a device action.

**Comment by RogerSelwyn** [comment]
However I will look to see if I can add device actions as well.

**Comment by mogusbi-motech** [comment]
Amazing (I say this as a total HA novice). That is exactly what I needed to do so thanks. Yeah an action would probably assist anyone new to this like me

**Comment by RogerSelwyn** [comment]
Device Actions added with this release - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.11.5
