### ISSUE TITLE
[BUG] Apple Remote doesn’t work although accessory exposed

### ISSUE THREAD

**Issue by andypburke** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#156]
### Describe the bug

I have exposed the SkyQ media player to Homekit as an accessory and it appears as a TV device and I can change channels.  However, when I try and use the Apple Remote the keys don’t work.  Am I doing something wrong?

### To reproduce

Open Apple Remote and select SkyQ device.  Pressing keys doesn’t do anything on Sky box 

### Expected bahavior

Select and up and down keys expected to work 

### What version of SkyQ has the issue?

2.11.3

### What was the last working version of Sky Q Integration?

2.11.3

### What version of Home Assistant Core has the issue?

core-2023.7.1

### Configuration type

UI

**Comment by RogerSelwyn** [comment]
Should be fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.11.4

**Comment by andypburke** [comment]
Thanks @RogerSelwyn.  Installed new version and this works perfectly.  👍🏻
