### ISSUE TITLE
Inconsistent results with channel changing

### ISSUE THREAD

**Issue by simps100** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#157]
### Describe the bug

Hi

I am seeing some strange inconsistent results when adding channels to my sky q boxes in HA:

Living Room Sky q (main box)
Works perfectly - channel list is displayed in apple home and home assistant without issue, can change channels etc.
![IMG_9250](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/60661312/47fe57b3-4cd9-418b-b53f-511a54d60e5f)

Bedroom Sky q mini box

In apple home all channels show as same name (names are correct in HA media player) , changing channel works but not able to know what channel you are selecting.

![IMG_9251](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/60661312/36331e1d-7437-42ae-94e1-fb5e9aa88f62)

Kitchen Sky q mini box 

![IMG_9249](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/assets/60661312/22067040-9db1-4115-8b58-63409d3b75d2)

this one is the least functional one, the channels display in HA media player but changing channel does not work, all channels show as same in Apple home like bedroom, but changing channel also does not work here. Only difference is this box is wifi?

### To reproduce

Add channels to main sky q box and then minis - main sky q box seems to be fine but issues occur with minis 

### Expected bahavior

To see same channel selection list for mini boxes 

### What version of SkyQ has the issue?

2.11.5

### What version of Home Assistant Core has the issue?

Core-2023.8.1

### Configuration type

UI

**Comment by RogerSelwyn** [comment]
Have you tried restarting Home Assistant after adding channels, it may well be to do with the HomeKit Bridge which I don't think will update input sources (which is what channels are configured as) until a restart.

I've just gone through and configured up my Sky Q and Mini to Home, after a restart all was fine. That of course doesn't mean there isn't a bug somewhere for you. I'm interested that it is showing the device name in the channel list, because I don't think it should do that. Have you configured a custom source with the device name in it?

Are there any errors in the logs?

**Comment by simps100** [comment]
Hey

Thanks for the reply - I've been doing some more messing about with this this morning. I did try restarting HA but it didn't make a difference but I've managed to get the channel list in apple home to work now by removing the Sky Q accessory bridge for that box and recreating it after adding the channels.

As for the changing channel issue I think it's more of a sky issue - when my 2 mini boxes come out of standby they start up with the Home Screen open and channel changing don't work until I press back on the remote to take the channel into full screen - only then the channel changing works - interestingly the main sky q box switches on straight into the channel so works - I'm not sure why the boxes do different things but that's sky I guess! 

I'm not sure if there is some sort of config which would be possible to help with this by pressing the return button before inputting the channel number?

I've looked in the sky box preferences and there don't seem to be an option to disable this.

Thanks
Marc

**Comment by RogerSelwyn** [comment]
You can use the Apple Remote to hit the back button from your iOS device.  Or you could create specific custom sources with back in it. I could possibly add an option for back to be added to each source, but I think it’s niche case.

**Comment by simps100** [comment]
> You can use the Apple Remote to hit the back button from your iOS device.  Or you could create specific custom sources with back in it. I could possibly add an option for back to be added to each source, but I think it’s niche case. 

An option to press the back button before each source would be appreciated if it wasn't too much work - am still fairly new to HA and getting everything up and running slowly but surely! I will look into creating custom sources which can do this in the meantime. Thanks for your help !

**Comment by simps100** [comment]
```
    skyq_bbconelonhdkitchen:
      value_template: '{{"off"}}'
      friendly_name: 'BBC One Lon HD in the Kitchen'
      turn_on:
        - service: media_player.select_source
          data:
            entity_id: media_player.kitchen_sky_q
            source: 'BBC One Lon HD'
        - delay:
            seconds: 10
      turn_off:
        stop:
```

Hi - is it in the above configuration I can add in a option to press the back button?

**Comment by RogerSelwyn** [comment]
No. Please look at the documentation on custom sources.

**Comment by RogerSelwyn** [comment]
https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/configuration_ui.html#custom-sources

**Comment by simps100** [comment]
Thanks very much for your help will look at setting these up for my mini boxes.

**Comment by RogerSelwyn** [comment]
There isn't a way to distinguish a HomeKit "select source" command from an HA (Lovelace or automation) driven service call to "select source". So I don't think I can add an option for "back" for HomeKit, and I don't want to break people's existing configs by adding a "back" to all select sources.

I should add the list of sources is provided in a consistent manner to HomeKit or Lovelace (media player card), the only manipulation I do is to merge the channel and custom sources and add the current channel if it isn't in the base lists.

**Comment by RogerSelwyn** [comment]
Personally I find it frustrating that you can change channel in Apple Home, and control play/stop/volume/etc using Apple Remote. But I have no control over this, it is how HA have represented a "TV" to HomeKit, and probably how Apple supports them.

I'll continue to think on this for a few days, and close if I can't come up with anything.

**Comment by simps100** [comment]
Hi,

Thanks for the response - just to add the issue exists in Lovelace too not only HomeKit - when the box is first switched on from standby the channel switcher in Lovelace also fails because I am guessing it can't input a channel number on the default sky Home Screen.

It's more annoying you can't disable that screen on the Minis (don't happen on my main sky q box) than anything.

Not sure if an optional advance feature check box to include a back button press before inputting a channel number would be possible? I have done some testing on my sky box and haven't found a scenario where pressing back before entering a number causes an issue - but I do appreciate it's a niche feature which may not be used much.

Thank you again
Marc

**Comment by RogerSelwyn** [comment]
I'm planning to add it as an option for channel sources. Not for custom sources, because you can add that yourself.

**Comment by simps100** [comment]
> I'm planning to add it as an option for channel sources. Not for custom sources, because you can add that yourself.

Thank you - I think this will fix the issue am facing if I select this option.

**Comment by RogerSelwyn** [comment]
Please try this release - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.11.6

**Comment by simps100** [comment]
> Please try this release - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.11.6

Just gave this version a go and the backup option solves the issue I've seen on the mini box - thank you very much for helping with this!
