### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by vincepg13** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#158]
**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
Support for sky stream

**Describe alternatives you've considered**  
None

**Additional context**  
Is it possible to add support for sky stream devices into HA?

**Comment by RogerSelwyn** [comment]
Sorry, this isn't possible. See:

- https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/issues/142
- https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/issues/124

As I've said elsewhere, I would if I could, but Sky have made it impossible, probably on purpose.
