### ISSUE TITLE
How do I add apps to the source list

### ISSUE THREAD

**Issue by dev-bash** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#159]
### Describe the bug

There are no "apps" (Netflix, Youtube) in the lost to select custom sources. How do i add them?

### To reproduce

.

### Expected bahavior

.

### What version of SkyQ has the issue?

latest

### What version of Home Assistant Core has the issue?

latest

### Configuration type

UI

**Comment by RogerSelwyn** [comment]
You need to create your own custom source as shown in the ui config page, with the appropriate button presses to activate the application. 

https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/configuration_ui.html#custom-sources

Available button presses are shown here.

https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/buttons.html

**Comment by dev-bash** [comment]
When I go to configure from the Ui. There is no text and just blank boxes

**Comment by RogerSelwyn** [comment]
Please post a screen shot

**Comment by dev-bash** [comment]
I managed to figure it out with out the text!

**Comment by RogerSelwyn** [comment]
It seems strange there is no text, that suggests your translations aren’t working. Are you using something other than English, German or Italian?

**Comment by dev-bash** [comment]
I’m on English, I had to set it up without text too

**Comment by RogerSelwyn** [comment]
Never heard of that, did you install from HACS?

**Comment by RogerSelwyn** [comment]
No further input.
