### ISSUE TITLE
Access manually added channels and apps

### ISSUE THREAD

**Issue by DoubtfulBadger** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#163]
Living in Ireland, we don't get EPG access to UK channels. For example, ITV. It's possible to add the channels by going to "settings", "manual tuning". Switching to these channels is done by selecting "home" then pressing "down" 12 times (then a few more downs, etc.) Similarly, I can go to apps to select, say, Apple TV+.

I've written an automation to do this but I wonder if there is a more elegant way.

I've attached my ITV4 HD and my Apple TV+ script.
[Apple TV+.txt](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/files/12807470/Apple.TV%2B.txt)
[Sky ITV4 HD .txt](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/files/12807471/Sky.ITV4.HD.txt)

**Comment by RogerSelwyn** [comment]
You can set up a custom source sending multiple button presses:-

https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/configuration_ui.html

Or use a device action or entity service call:-
https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/automation_actions.html
https://rogerselwyn.github.io/Home_Assistant_SkyQ_MediaPlayer/buttons.html

If you mean is there a call where you can just say start Apple TV, no there isn’t. All you can send is what is on the physical remote (not a complete truth, it could be told to record a specific programme like you can using SkyGo app, but I’m not into providing a full epg browser).

**Comment by RogerSelwyn** [comment]
If the SkyGo so can’t do it, then the api isn’t on the box to do it. 

And they only recently added the ability to send buttons to the box.

**Comment by DoubtfulBadger** [comment]
Hi Roger, Thanks for the quick response. I have used configuration to allow access to my favourites. For example, I use a single "1" to go to BBC1 (which, incidentally, is on 141 for me). For the specialised stuff it's going to be easier for me to use the HA automation that I sent to you as it's easier to edit.

Thanks for the Sky Q integration, it's really handy. Keep up the good work.
