### ISSUE TITLE
Debug funtion[Feature Request]

### ISSUE THREAD

**Issue by dieterbahr** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#165]
Sorry that i ask on this way, but i didn't found an other way.

the integration works now fine since a long time.
When it dosen`t works fine you told me to switch debug function, but i forgot where it was. So the debug function works since this time. How can i switch it of.

Regards Dieter

**Comment by RogerSelwyn** [comment]
It's in config.yaml under the logger heading.
