### ISSUE TITLE
[Feature Request] Enable capability to perform Pre-Channel Change action whilst using Home Assistant Media Player for channel change

### ISSUE THREAD

**Issue by ChrisHammond56** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#172]
**Is your feature request related to a problem? Please describe.**  
When using the main Home Assistant GUI to change channel via the drop-down list (not using switches), the box can change channel fine. However, should the box be at the PIN prompt, or in an APP for example. The channel change will not work.

**Describe the solution you'd like**  
What would be useful is a pre-channel or 'always perform this action' before a channel change. For example, if the page is waiting for the PIN, then performing the PIN KEYS (with an optional BACKUP) then the channel would work. This way, the pre-action would be (1)PIN, (2)BACKUP, (3)CHANNEL?

**Describe alternatives you've considered**  
I am currently using an automation to change channel with the correct sequence, and this seems to be stable. However, the media player GUI does not use automations for channel switching

**Additional context**  
One option could be link the channel change to an automation in HA, but not sure if that is scalable. Note: I thought I did see an option to have a 'perform for every channel', but cannot seem to find that.

**Comment by RogerSelwyn** [comment]
This  may be very difficult for me to develop since I no longer have a SkyQ box (sorry cost was getting ridiculous). You could potentially string multiple service call together to do what you need, or create a custom source with the relevant commands string together.

**Comment by ChrisHammond56** [comment]
I am open to Beta testing code if that's an option. The services approach isn't really viable, as I am doing that with the automation via a WebHook currently (but that's not via the GUI). The custom source seems even more longwinded as I would need to create many custom sources (unless I have misunderstood your potential solution). Thanks

**Comment by RogerSelwyn** [comment]
I’m afraid I can’t create beta test code with no box to develop again. I’m open to a PR.

**Comment by ChrisHammond56** [comment]
That sounds promising. I would need to fit it in with my very limited spare time, but that's one option I suppose....

**Comment by RogerSelwyn** [comment]
To be honest I’ve considered archiving the integration, but I know if I do HACS will remove it and that step is a bit unneeded. I can generally fix things caused by core changes, but developing new is very difficult.
