### ISSUE TITLE
[Feature Request] Lists of scheduled and existing recordings

### ISSUE THREAD

**Issue by RealGandy** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#175]
**Describe the solution you'd like**  
Is there any way of getting a sensor that contains a list of current recordings on the box, perhaps limited to a set number if needed?

Similarly, a sensor containing a list of all scheduled recordings, expanding the current 'next recording' that is currently possible.

**Comment by RogerSelwyn** [comment]
Whilst this might be possible, I no longer have access to a SkyQ from my dev environment, simply expensive for too little gain. 

Consequently I can’t add any new features. If you can submit a PR, I can merge it. 

Alternatively, there is a rest api in the box that you could possibly pull the data from yourself.

**Comment by RealGandy** [comment]
Ok, thanks... I'll take a look at the API and see what I can scrape from there.
