### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SRJohnston** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#176]
### Describe the bug

Not so much a bug, but I used to use the stop command in routines when turning the sky q box off.  So when I was playing a recording, I could run an automation which pressed stop, then turned the sky q box off.  

This used to work on both the sky Q 2tb box and the sky mini box, but with in the last few weeks it has stopped working.

### To reproduce

action: media_player.play_media
data:
  media_content_type: skyq
  media_content_id: stop
target:
  entity_id: media_player.skybox

### Expected bahavior

Should stop current playing program

### What version of SkyQ has the issue?

2.11.11

### What version of Home Assistant Core has the issue?

2024.12.3

### Configuration type

UI

### Additional information

```txt
It would be awesome if this could be checked out
```

**Comment by SRJohnston** [comment]
I do love this integration and it is one of the main reasons I started using Home Assistant.  It should be a core integration by now!

**Comment by RogerSelwyn** [comment]
Unfortunately I no longer have a sky box to test against. If Sky have updated the firmware to behave differently, I'm unlikely to be able to figure out what has changed.

**Comment by SRJohnston** [comment]
Sorry to hear that. it is not the end of the world.  I can still use backup as a work around, This is still a brilliant intergration!

**Comment by SRJohnston** [comment]
Hey was just having a look through your code.  I am no coder by any means, but is there a reason this stop line is hashed out?

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/blob/master/custom_components/skyq/const.py

FEATURE_BASE = (
    MediaPlayerEntityFeature.TURN_OFF
    | MediaPlayerEntityFeature.TURN_ON
    | MediaPlayerEntityFeature.PAUSE
    | MediaPlayerEntityFeature.PLAY
    **# | MediaPlayerEntityFeature.STOP**
    | MediaPlayerEntityFeature.NEXT_TRACK
    | MediaPlayerEntityFeature.PREVIOUS_TRACK
    | MediaPlayerEntityFeature.SELECT_SOURCE
    # | MediaPlayerEntityFeature.SEEK
    | MediaPlayerEntityFeature.PLAY_MEDIA
)

**Comment by RogerSelwyn** [comment]
I don’t remember, but that is the features presented to ha core, it won’t change what button commands can be sent.

**Comment by RogerSelwyn** [comment]
Probably there is only play/pause. There is no stop button on a sky remote

**Comment by SRJohnston** [comment]
Yes your right.  I just had a look.  As a work around I can use the backup
command.  It works well

I definitely remember the stop command working before.  But I really
appreciate you looking into it!  We can go ahead and close this off.

Out of curiosity what are you using instead of Sky?

Cheers Stephen

**Comment by RogerSelwyn** [comment]
Smart tv, I have Netflix, Apple TV and Prime. I also have DiscoveryPlus from elsewhere. That covers everything I need for less that 50% of what they wanted. They keep pestering me at  cheap prices, but they are now dear to me.

**Comment by SRJohnston** [comment]
I was thinking of getting rid of any as well.  I like the convenience of
Sky but not the cost.

If I could get my TV Arial sorted or get internet TV that would be cool!

**Comment by RogerSelwyn** [comment]
You will want an internet tv would think. Get rid of sky and you could buy one pretty quick.

**Comment by SRJohnston** [comment]
100% Ideally I would get 2.  One for my living room and kitchen.  I need to look into it, but if I could get an internet streaming tv that I could plug a usb hdd into and record it would be ideal.  Like you I have Netflix, plex, prime and discovery plus.  So covered for tv.

**Comment by SRJohnston** [comment]
Thanks for all your help.  I am using backup,backup as a work around
