### ISSUE TITLE
[BUG] Hi guys - I’m seeing a new error in my logs for the SkyQ custom components.  2020-07-25 14:26:51 ERROR (SyncWorker_2) [pyskyqremote.skyq_remote] E0020 - Invalid command: 192.168.1.14 : Sky 2020-07-25 14:27:10 ERROR (SyncWorker_1) [pyskyqremote.skyq_remote] E0020 - Invalid command: 192.168.1.14 : Home 2020-07-25 14:27:17 ERROR (SyncWorker_5) [pyskyqremote.skyq_remote] E0020 - Invalid command: 192.168.1.14 : Home  Pressing any of the buttons on my Lovelace card except the power button and pause/fast forwards/back have no effect except to generate this error.  Thanks for any help

### ISSUE THREAD

**Issue by hodgei** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#18]
**Describe the bug**  

**To Reproduce**  
1. What were you doing/watching at the time ?
2. What channel were you on?
3. What time did the problem occur?
4. Where are you (bear in mind component supports GBR/ITA at the moment)?

**Expected behavior**  

**Screenshots**  

**Component versions**  
1. What version of SkyQ component are you using?
2. What was the last version where the problem was not shown?

**Your configuration**  
How have you setup your devices, by UI or YAML?

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
```yaml
media_player:
 - platform:  skyq
   name: SkyQ Living Room
   host: 192.168.0.10
   live_tv: True
   country: "UK"
   sources:
      SkyOne: '1,0,6'
      SkyNews: '5,0,1'
````
**Output of HA logs**  
Paste the relavant output of the HA log here.

**Additional context**

**Comment by RogerSelwyn** [comment]
Please can you also include details of what version you are using and when did it last work. Ideally it would also help if you provide HA certain inspiration as well. Also provide details of your Lovelace configuration.

**Comment by hodgei** [comment]
I do apologise for the cr@p formatting on the original report.
So - I’m in the UK - trying to use the component.
My Lovelace card has the power button and fast forward/pause/back buttons which currently work and 3 rows of buttons which all give the error.
2020-07-25 13:57:13 ERROR (SyncWorker_1) [pyskyqremote.skyq_remote] E0020 - Invalid command: 192.168.1.14 : Select
2020-07-25 13:57:15 ERROR (SyncWorker_4) [pyskyqremote.skyq_remote] E0020 - Invalid command: 192.168.1.14 : Dismiss
2020-07-25 13:57:17 ERROR (SyncWorker_3) [pyskyqremote.skyq_remote] E0020 - Invalid command: 192.168.1.14 : Dismiss

Thanks.

**Comment by RogerSelwyn** [comment]
Sorry, but I still need a copy of the Lovelace configuration and the details of what version of the integration you are using.

**Comment by hodgei** [comment]
Sorry Roger - just getting to grips with this...

Lovelace : 

card: null
cards:
  - entity: media_player.living_room_tv
    type: 'custom:mini-media-player'
  - entity: media_player.sony_mega_amp
    icon: 'mdi:surround-sound'
    type: 'custom:mini-media-player'
  - artwork: cover
    background: >-
      https://wi-images.condecdn.net/image/m9qkOnPpZnz/crop/1620/f/screen-shot-2015-11-18-at-100440.jpg
    entity: media_player.sky_q
    hide:
      power_state: false
      source: true
      volume: true
    icon: 'mdi:satellite-uplink'
    more_info: true
    name: SkyQ
    shortcuts:
      buttons:
        - icon: 'mdi:chevron-up'
          id: CHup
          type: source
        - icon: 'mdi:chevron-down'
          id: CHdn
          type: source
        - icon: 'mdi:record-rec'
          id: Record
          type: source
        - icon: null
          id: Sky
          name: Sky
          type: source
        - icon: null
          id: TVGuide
          name: Guide
          type: source
        - icon: 'mdi:home-outline'
          id: Home
          type: source
        - icon: 'mdi:menu-open'
          id: Sidebar
          type: source
        - icon: 'mdi:keyboard-return'
          id: Dismiss
          type: source
        - icon: 'mdi:information-variant'
          id: I
          type: source
        - icon: 'mdi:arrow-right-thick'
          id: Right
          type: source
        - icon: 'mdi:arrow-left-thick'
          id: Left
          type: source
        - icon: 'mdi:arrow-up-thick'
          id: Up
          type: source
        - icon: 'mdi:arrow-down-thick'
          id: Down
          type: source
        - icon: null
          id: Select
          name: Select
          type: source
        - icon: null
      columns: 5
      hide_when_off: true
    type: 'custom:mini-media-player'
title: Entertainment
type: 'custom:vertical-stack-in-card'

Integrations screenshot : 
<img width="1440" alt="Screenshot 2020-07-25 at 15 11 03" src="https://user-images.githubusercontent.com/1457673/88458917-33049080-ce89-11ea-8343-05309e874801.png">

**Comment by RogerSelwyn** [comment]
For buttons it would be worth you re-reading the documentation. They should look like this.  The list of available commands are shown in the documentation. 

```
shortcuts:
  buttons:
    - icon: 'mdi:chevron-up'
      id: channelup
      type: skyq
```

Or if you want to use ‘type: source’ then you need to define the name in your sources list.

**Comment by hodgei** [comment]
Blast - I’d grabbed my Lovelace card from an earlier post and it worked in the old HACS integration.

All fixed now - sorry for the trouble.

Iain.

**Comment by RogerSelwyn** [comment]
No worries. 😀
