### ISSUE TITLE
Option not load[BUG]

### ISSUE THREAD

**Issue by djgragra** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#19]
Yesterday I have install a update from Hacs but after the installation it's impossible to load the option.
The screen remain on "Wait, Install the integration"
![Schermata 2020-07-27 alle 12 24 50](https://user-images.githubusercontent.com/65872226/88532074-3708ed80-d004-11ea-8794-ab1cd8c87054.png)

**Comment by RogerSelwyn** [comment]
What version of Sky Q are you on. Also what version of Supervisor and HA?  Then I can try to much version and check it out.

**Comment by RogerSelwyn** [comment]
I notice you changed Supervisor to HACS. Please provide details of your configuration (screenshots are fine) and post any errors reported in the logs.

**Comment by RogerSelwyn** [comment]
Also, did you reboot HA after the upgrade?

**Comment by djgragra** [comment]
Thanks for your answer.
Yes I update from Hacs not from Supervisor.
I attached the log file, I try to restart HA and Raspberry many times but when I push OPTION in Integration the system remain in wait to update as you can see in the screenshot.

Graziano Melzi

Please consider the environment before printing this e-mail notice
Il 27 lug 2020, 13:38 +0200, RogerSelwyn <notifications@github.com>, ha scritto:

**Comment by RogerSelwyn** [comment]
What version of Sky Q are you on? 

Please provide logs by attaching straight on GitHub rather than via email response. 

Does options work on your other integrations?

Please provide details of your configuration.

**Comment by djgragra** [comment]
Thanks for your answer.
Yes I update from Hacs not from Supervisor.
I attached the log file, I try to restart HA and Raspberry many times but when I push OPTION in Integration the system remain in wait to update as you can see in the screenshot.

My configuration
Raspberry PI 4 4GB
Home assistant 0.113.1
Sustem HassOs 4.11

With other integration like Philips Hue configure works!
I don't know what is the SkyQ version but I update to the last version 2 days ago.

[home-assistant.log](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/files/4982064/home-assistant.log)
![Schermata 2020-07-27 alle 12 24 50](https://user-images.githubusercontent.com/65872226/88543501-5873d480-d018-11ea-95db-68d1adda5bc8.png)

**Comment by RogerSelwyn** [comment]
You can see what version you have installed by going into HACS and clicking on the integrations card. Looking at your logs, you have lots of errors like this, I'd suggest you should resolve these. 

`020-07-27 14:09:16 WARNING (MainThread) [homeassistant.components.template] Template switch 'skyq_pausesoggiorno' has no entity ids configured to track nor were we able to extract the entities to track from the value template(s). This entity will only be able to be updated manually`

It may be best for you to uninstall SkyQ and then reinstall. It should create with the same entity names, so any dependencies shouldn't break. If after that you still can't get into Options, then it would be good to know if any new errors are generated when you click on Options.

**Comment by djgragra** [comment]
![Schermata 2020-07-27 alle 21 50 00](https://user-images.githubusercontent.com/65872226/88585594-904c3d80-d053-11ea-905a-3fda0f96c643.png)
Okay, I'll try reinstalling and let you know.
The SkyQ version is 2.3.0

**Comment by djgragra** [comment]
I reinstall the integration and now work fine.
The channels are many less than before but it is not a problem. In Google Home the new channel non sync but this problem I think not depending from the integration.
I'll update you in case there are new critical issues. Thanks for the support

**Comment by djgragra** [comment]
Mi correggo, i canali ci sono tutti solo che dal 500 inpoi vengono mischiati con i canali 5000 del digitale terrestre DVB

**Comment by RogerSelwyn** [comment]
In theory it should show all channels returned by the box, so not sure why it would only show from 500 on. I'll take a look. 

If you configured channels via YAML before, I can guide how to do the same vis the UI.

**Comment by RogerSelwyn** [comment]
Ahh, I misunderstood what you said. They are all there. I wasn't aware there were 4 digit channels, we don't have those in the UK apart from Radio channels, which I have separated out.

From this URL, can you provide me the details from one of the 5000 series channels. You will need to change the IP.

http://192.168.1.22:9006/as/services

**Comment by RogerSelwyn** [comment]
Fixed by v2.3.1
