### ISSUE TITLE
Programme Details Value

### ISSUE THREAD

**Issue by c0nt4x** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#25]
Hi

On the media player card it shows the channel and programme title. 

I’m wondering if it’s possible to reference the programme title in a template?

Basically I’m looking to identify when the programme contains a specific string I want to trigger an automation. 

I don’t know though if I can reference that in a template. If it’s possible can you tell me please what the variable is that I reference. 

Thanks

**Comment by RogerSelwyn** [comment]
This shows an example of where I use the title in a template sensor.

```
    sky_media_title:
      friendly_name: "Media Title"
      value_template: "{{ state_attr('media_player.sky_q', 'media_title') }}"
```

**Comment by c0nt4x** [comment]
Can the programme value/state also be referenced, Roger? So, for example “Panorama”?

**Comment by RogerSelwyn** [comment]
I'm afraid I'm no expert on HA templates, but I think if you have a look at the documentation on templating and template sensors you should be able to find what you need. This is nothing specific to the Sky Q integration, npjust general HA templating.

**Comment by c0nt4x** [comment]
Ah, ok, so the programme title that shows in the dashboard, next to the channel name, is down to HA and not the integration? 

I’ll see if someone can help re HA then.

Thanks for you help.
