### ISSUE TITLE
[BUG] media browser doesn’t populate 

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#26]
Restart home assistant. 
Watch a recording in sky q. 
Open media browser. 

It doesn’t populate. 

Stop recording. 
Re-open. 
Populates ok. 

Play recording. 
Open browser. 
It now works ok from cached info.

**Comment by RogerSelwyn** [comment]
Not sure why that should make a difference, but I’ll take a look tomorrow.

**Comment by RogerSelwyn** [comment]
I assume you tried to go into browser while watching a recording?

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.4.0.alpha6
