### ISSUE TITLE
Buttons List to use if you use "mini-media-player" [Feature Request]

### ISSUE THREAD

**Issue by bluenazgul** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#30]
**Is your feature request related to a problem? Please describe.**  
Missing Button Commands for using "mini-media-player" 

**Describe the solution you'd like**  
have a list with supported Button commands

**Describe alternatives you've considered**  
example code for the "mini-media-player" Screenshot that you use

**Additional context**  
my current working buttons

type: 'custom:mini-media-player'
entity: media_player.sky_q
shortcuts:
  columns: 4 # Max buttons per row
  buttons:
    - icon: 'mdi:chevron-up'
      id: channelup
      type: skyq
    - icon: 'mdi:chevron-down'
      id: channeldown
      type: skyq
    - icon: 'mdi:home'
      id: home
      type: skyq
    - icon: mdi:magnify
      id: search
      type: skyq

**Comment by RogerSelwyn** [comment]
All the available commands are available here:

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#supported-buttons

It doesn't matter whether you are using MMP, or service automation or anything else, they are the same list of commands.

**Comment by bluenazgul** [comment]
Thanks, finaly got it working
![image](https://user-images.githubusercontent.com/171537/95783818-f18ac100-0cd2-11eb-919f-23c94fb626ad.png)

Now only my other "Feature Request" missing
