### ISSUE TITLE
Option to cache more than 20 Entries to Media Browser [Feature Request]

### ISSUE THREAD

**Issue by bluenazgul** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#31]
**Describe the solution you'd like**  
Add an UI Option to cache more than 20 Entries to Media Browser
- 20 (default)
- 25
- 30
- all (maybe laggy)

**Describe alternatives you've considered**  
if not possible via UI Option, maybe via config file

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.4.4
