### ISSUE TITLE
[BUG] Device Class causes error in Homekit

### ISSUE THREAD

**Issue by Niccc17** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#36]
Sources out of sync when exposing to HomeKit as Television Media Player

![Schermata 2020-11-03 alle 13 51 12](https://user-images.githubusercontent.com/60943319/97987469-a6e4fc00-1ddb-11eb-9170-ba7c1ee5d0d5.png)
![IMG_3141](https://user-images.githubusercontent.com/60943319/97987481-ac424680-1ddb-11eb-9d31-e5b1444d968a.jpg)
![IMG_3142](https://user-images.githubusercontent.com/60943319/97987488-af3d3700-1ddb-11eb-8bac-2c2a9ae12a7e.jpg)

**Comment by Niccc17** [comment]
I'm fairly new to GitHub and I'm sorry if this wan't the right thing to do. I have this issue and don't know how to fix t, the sources in HA are updated, while in HomeKit are out of sync after 15-20 seconds of me changing the source in the Home app.

**Comment by RogerSelwyn** [comment]
I think that is a query for HomeKit I'm afraid. The integration provides the data to Home Assistant, if it shows correct in there then there is no more involvement of the integration. 

I'll try to take a look at the error in Homekit and see if I can figure what is triggering it.

**Comment by RogerSelwyn** [comment]
If you are up for it, please edit const.py and change DEVICE_CLASS from 'tv' to 'receiver'. The restart Home Assistant. If that works for you, then I'll make the change and release.

I don't use Homekit outbound (I do use Homekit Controller for Nest via Hoobs), so I haven't checked if the paired other end of HK is seeing the right thing.

**Comment by RogerSelwyn** [comment]
Closed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.4.7
