### ISSUE TITLE
Allow Channel Change when Sky Box is on Home Menu

### ISSUE THREAD

**Issue by grubhunter66** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#37]
Firstly this has saved me a load of work. Very nice addition to Home Assistant. Thank You.

When the Sky Q Box is initially turned on or if someone has navigated to the main menu the "browse media" or "Select Source" will not allow the channel to be changed.
This can be fixed by adding "backup" to the channel description. E.G
   sources:
      BBC 1: 'backup,1,1,5'
Unfortunately this breaks the image displayed in the Library list (default grey TV is shown instead)
Would it be possible to filter out "backup," when parsing the list?
I'm Python is not good, but will try if your time is limited.

**Comment by RogerSelwyn** [comment]
Closed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.4.8

**Comment by grubhunter66** [comment]
Works a Treat 👍
