### ISSUE TITLE
Unknow error in media library

### ISSUE THREAD

**Issue by radeon79** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#40]
In the media library i receive a unknow error.
In the registry have this errors:
X0010U - Image file check failed: http://my_ip_address:8123/local/community/skyq/rai 3.png : Server disconnected
X0010U - Image file check failed: http://my_ip_address:8123/local/community/skyq/class tv moda.png : Server disconnected
X0010U - Image file check failed: http://my_ip_address:8123/local/community/skyq/sky sport serie a.png : Server disconnected
X0010U - Image file check failed: http://my_ip_address:8123/local/community/skyq/sky sport info.png : Server disconnected
X0010U - Image file check failed: http://my_ip_addess:8123/local/community/skyq/dazn2.png : Server disconnected

The change channel is working fine. How to solve???
I have already copied a png image like rai 3.png in the path without succcess.

**Comment by radeon79** [comment]
i have this error also:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skyq/classes/mediabrowser.py:87
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:03:06 (10 occurrences)
Last logged: 15:03:55

[140020819607504] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1066, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/skyq/media_player.py", line 427, in async_browse_media
    return await self._media_browser.async_browse_media(
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 35, in async_browse_media
    channellist = await self._async_prepareChannels(hass, channel_list)
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 63, in _async_prepareChannels
    channels = await asyncio.gather(
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 87, in _async_get_channelInfo
    programme = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 223, in getProgrammeFromEpg
    sidint = int(sid)
ValueError: invalid literal for int() with base 10: 'M217c-107-2c7-ffff'

**Comment by RogerSelwyn** [comment]
Are this applications on the Sky Q box, because they look like channel names? You should only be able to get that error for an application. Was there a full stack traces for the X0010U errors?

Also, what do you get if you run this command against your box:
http://192.168.1.22:9006/as/system/information

Then also provide me the list of sources you have configured for your Sky Q box, and the time at which these errors occurred.

**Comment by RogerSelwyn** [comment]
Also have you ensure the image is available at the url shown in the log, from the location you are accessing HASS from.

**Comment by radeon79** [comment]
hello this is my system/information
{
   "ASVersion" : "Q140.000.34.00-AS_20.4.2",
   "CAType" : "VIDEOGUARD",
   "DRMActivationStatus" : true,
   "IPAddress" : "192.168.2.7",
   "MACAddress" : "xx:xx:xx:xx",
   "activeStandby" : false,
   "airplayID" : "Sky8445",
   "btID" : "Sky8445",
   "cable" : false,
   "chipID" : "xxxxx",
   "deviceID" : "xxxxxxxxxx",
   "deviceType" : "GATEWAYSTB",
   "gateway" : true,
   "gatewayIPAddress" : "not MR",
   "hardwareModel" : "ESi-160",
   "hardwareName" : "Amidala",
   "hdrCapable" : true,
   "householdToken" : "000002BE00000054026A614521FA742F9938406793BCF6591800C1001F2C0E49461FD4BC61D5000000000000001E000000000000001649543030303030333331383535DDC3816495FBC7407DC4899468EB21AC",
   "localIRDatabase" : true,
   "manufacturer" : "HUMAX",
   "meshEnabled" : false,
   "modelNumber" : "Q140.000.34.00L (58j9mx4)",
   "networkVersion" : "2.00",
   "numDTTTuners" : 1,
   "pipCapable" : true,
   "purchasebalance" : "0.01",
   "purchaselimit" : "30.01",
   "receiverID" : "C 1CE2368901xxx",
   "serialNumber" : "xxxxxxx",
   "subscriberID" : "17470469",
   "systemUptime" : 43104,
   "uhdCapable" : true,
   "versionNumber" : "6763A3",
   "viewingCardNumber" : "450519780",
   "wakeReason" : "ECO"
}

**Comment by radeon79** [comment]
my deviceinformation:
{
   "ASVersion" : "Q140.000.34.00-AS_20.4.2",
   "IPAddress" : "192.168.2.7",
   "bouquet" : 25175,
   "countryCode" : "ITA",
   "gateway" : true,
   "hardwareName" : "Amidala",
   "householdToken" : "000002BE00000054026A614521FA742F9938406793BCF6591800C100222FCF6417DEFB0825C9000000000000001E000000000000001649543030303030303030303030303037333331383535BE0FE915936753E79C2E1DCC9030D410",
   "modelNumber" : "Q140.000.34.00L (58j9mx4)",
   "pipCapable" : true,
   "serialNumber" : "xxxxx",
   "streamingCapable" : false,
   "subbouquet" : 7,
   "subscriberID" : "17470469",
   "versionNumber" : "6763A3"

**Comment by radeon79** [comment]
In the attached my yaml. I receive the error for Rai1, Rai2,rai3, sky sport serie A only.
[sky_q.zip](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/files/5831270/sky_q.zip)

**Comment by radeon79** [comment]
![image](https://user-images.githubusercontent.com/33173547/104938505-7c084e00-59af-11eb-8224-e0b2b319f944.png)

**Comment by radeon79** [comment]
![image](https://user-images.githubusercontent.com/33173547/104938601-97735900-59af-11eb-8c52-f8b632085029.png)
if remove Rai1, rai2,rai3 and la7 from list not receive error.

**Comment by RogerSelwyn** [comment]
I believe those channels don't have EPG available via the source I sue. You will also not find them here - https://guidatv.sky.it/?vista=griglia. So I think it is defaulting to trying to find a local image for them, and failing because the url to them is invalid. By this I don't mean not found, but the url doesn't link to a valid host name. As per my previous query, it is with checking that the image file is actually accessible using the url shown in the log from the location you are accessing HA from.

I am in UK, so I can't simulate exactly, but I can get close. In the screenshot below, I have renamed your 'Rai 1' to 'Rai1' because the image url doesn't like having a space in it, and then I renamed my Netflix image to Rai1. You can see this works fine.

<img width="350" alt="Screenshot 2021-01-18 at 16 35 57" src="https://user-images.githubusercontent.com/7115783/104941897-96d8c380-59ab-11eb-94e3-feb2c6c2f380.png">

I get no errors in my log when I do this. You can see the other images weren't found, but because they would be at a valid url, no error is logged.

**Comment by radeon79** [comment]
Ok is clear. Is possible to fix this message for the channels without epg in the future versions??

**Comment by RogerSelwyn** [comment]
It would be better if you can fix your installation so it isn't generating an invalid url (I would validate the internal/external url in HA settings are correct), otherwise I would have to disable functionality that other users might be using. i.e. the ability for it to fall back to an image where the EPG isn't available.

**Comment by RogerSelwyn** [comment]
I will look at the other error with the invalid SID, and see if it can be resolved.

**Comment by radeon79** [comment]
but the my url is valid. Is possible for me to see the png in the browser:  https://192.168.2.5:8123/local/community/skyq/rai1.png (i have renamed the netflix png)

**Comment by radeon79** [comment]
i have discovered this new error in the log:
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skyq/classes/mediabrowser.py:87
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:16:23 (2 occurrences)
Last logged: 18:18:36

[139936525356768] Error handling message: Unknown error
[139936524631392] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4581ff91f0>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apid.sky.it', port=443): Max retries exceeded with url: /gtv/v1/events?from=2021-01-17T22:00:00Z&to=2021-01-18T23:59:59Z&pageSize=50&pageNum=0&env=DTH&channels=9115 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4581ff91f0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1066, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/skyq/media_player.py", line 427, in async_browse_media
    return await self._media_browser.async_browse_media(
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 35, in async_browse_media
    channellist = await self._async_prepareChannels(hass, channel_list)
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 63, in _async_prepareChannels
    channels = await asyncio.gather(
  File "/config/custom_components/skyq/classes/mediabrowser.py", line 87, in _async_get_channelInfo
    programme = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 231, in getProgrammeFromEpg
    epgData = self.getEpgData(sidint, epgDate)
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 195, in getEpgData
    programmesData = self._remoteCountry.getEpgData(
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/country/remote_it.py", line 31, in getEpgData
    epgData = self._getData(sid, channelno, queryDateFrom, queryDateTo)
  File "/usr/local/lib/python3.8/site-packages/pyskyqremote/country/remote_it.py", line 52, in _getData
    resp = requests.get(epgUrl)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='apid.sky.it', port=443): Max retries exceeded with url: /gtv/v1/events?from=2021-01-17T22:00:00Z&to=2021-01-18T23:59:59Z&pageSize=50&pageNum=0&env=DTH&channels=9115 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4581ff91f0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by RogerSelwyn** [comment]
> https://192.168.2.5:8123/local/community/skyq/rai1.png 

This url is different to the one shown in your initial post, which shows http not https. Is it also available at the http address?

For your last error, it looks like you (or Sky) are having a DNS error for the EPG url. I would suggest you validate you can access https://apid.sky.it from your HA server since I'm not seeing this error at my end.

You can try to use the below command from a terminal session, it should be obvious if it is accessible.

`curl 'https://apid.sky.it/gtv/v1/events?from=2021-01-17T22:00:00Z&to=2021-01-18T23:59:59Z&pageSize=50&pageNum=0&env=DTH&channels=9115'`

**Comment by radeon79** [comment]
no is not work with http: (empty response message) The curl command is ok in the terminal

**Comment by RogerSelwyn** [comment]
Please go check your HA general configuration settings and validate the internal url is configured with https in it.

**Comment by radeon79** [comment]
is configured with https: and is work for me for other functions.

**Comment by RogerSelwyn** [comment]
Well the skyq integration gets the url from HA, and in theory uses the internal one first, before trying to use the external url if the certificate for the internal one is invalid. It's not clear where it would get the http address from. Is the certificate on the internal address valid and issued from duckdns or the like?

**Comment by RogerSelwyn** [comment]
It might be worth turning on more detailed logging for skyq. 

Can you set `custom_components.skyq: debug` in your log config, and see if other info is produced.

**Comment by radeon79** [comment]
[home-assistant.log](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/files/5832055/home-assistant.log)

**Comment by RogerSelwyn** [comment]
I don't see the same x0010u error in there. It looks like you have some dns resolution error, which I don't think I can help you with, sorry. The access to that url has worked at some point, otherwise your screenshot near the start of this thread would not have shown the programme name and image. 

When you have fixed that, come back with a log showing the x0010u errors and I'll try to diagnose.

**Comment by radeon79** [comment]
this error is still present after any reboot of home assistant and after
the media library opened for the first time. No problem after this (i see
the images also for the channels without epg). This can help to solve this
issue?


Il giorno lun 18 gen 2021 alle ore 20:27 RogerSelwyn <
notifications@github.com> ha scritto:

**Comment by RogerSelwyn** [comment]
Sorry, it's not clear which error you mean. Is that the X0010U error, or the error to do with name resolution?

When you say you see images for channels without EPG, is that in the media browser or in the standard view?

Perhaps, you can state the exact steps you have followed, and provide the logs for those steps.

**Comment by radeon79** [comment]
i don't have more the X0010U error. The error only is for the name
resolution after any reboot only. I see the right images in the media
browser (i have put png files in the right path)
[image: image.png]

Il giorno mar 19 gen 2021 alle ore 10:12 RogerSelwyn <
notifications@github.com> ha scritto:

**Comment by RogerSelwyn** [comment]
If the X0010U errors are gone, then I guess you have solved that issue. To get the EPG to work properly, you need to solve your name resolution issue. This isn't something I can solve in the integration. You have shown that the URL is correct by testing it, if you are getting the errors then there is some problem with your setup.

You can reconstruct the the url using the information in the error. From the image you just posted, it looks like some channels get the EPG, since all of the channels access EPG from the same url, and if there is no EPG available, then this is handle so no data is returned.

You can see if you use this url, that the url still gets a response, whereas for you you are getting 'Name does not resolve'
https://apid.sky.it/gtv/v1/events?from=2021-01-17T22:00:00Z&to=2021-01-18T23:59:59Z&pageSize=50&pageNum=0&env=DTH&channels=588

**Comment by RogerSelwyn** [comment]
I have corrected the dates in this url - https://apid.sky.it/gtv/v1/events?from=2021-01-18T22:00:00Z&to=2021-01-19T23:59:59Z&pageSize=50&pageNum=0&env=DTH&channels=9115

**Comment by RogerSelwyn** [comment]
It maybe, that for some reason that your name resolution doesn't work straight after reboot, but then works later on. In which case the error is valid and will resolve itself when your name resolution starts to work. The Media Browser uses exactly the same logic to pull back the EPG, so if you browse to the channel do you get the name resolution again? I think the channels you have shown errors on are Fox Crime +1 and Digitale terrestre canale 455

**Comment by radeon79** [comment]
i have effectuated this test. I have reboot home assistant. after this i have i have writed in the terminal this command: curl 'https://apid.sky.it/gtv/v1/events?from=2021-01-18T22:00:00Z&to=2021-01-19T23:59:59Z&pageSize=50&pageNum=0&env=DTH&channels=9115'
with success (name resolution is ok)
after this i have opened the media library and i have the error....
reopened and is ok.  is strange.....

**Comment by radeon79** [comment]
do you test my current config please?  is different for the last file. I have added more channels now.
[sky_q.zip](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/files/5835116/sky_q.zip)

**Comment by RogerSelwyn** [comment]
I can't test your config completely, because I don't have an Italian SkyQ box to pull data back from which is needed to test it properly. 

I don't know why you get a name resolution issue, there is only one place in the code to make a call to the EPG at that url. So I could add exception handling, so that it is a more controlled error, but it would still be logged as at minimum an 'error' level, because clearly it is an error. That url should be accessible.

In theory you will only get the error once for each channel per day, because the integration caches data. 

Is it always the same channel that causes the error, as noted by the 'channels' parameter. You can look up that channel here - https://apid.sky.it/gtv/v1/channels?env=DTH - to find which channel it is. The channel parameter is taken from the 'id' attribute of the json output.

**Comment by RogerSelwyn** [comment]
Also before opening media browser, have you tried going through the various channels on your sky box to see if you can trigger the error. Finally looking at your list of channel, you have about 130 on there. The media browser will be trying to load all of them, I can imagine that will be very slow, and will be hitting that url very rapidly. Maybe there is some throttling going on. Do you really need that many items in your source list? Looking at your config, you are caching 8 of them, which means every time you open media browser it will re-load them.

**Comment by RogerSelwyn** [comment]
As an fyi I have got a fix in progress for this error. Just waiting to bottom out this other problem of name resolution.

```
[140020819607504] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/media_player/init.py", line 1066, in websocket_browse_media
payload = await player.async_browse_media(media_content_type, media_content_id)
File "/config/custom_components/skyq/media_player.py", line 427, in async_browse_media
return await self._media_browser.async_browse_media(
File "/config/custom_components/skyq/classes/mediabrowser.py", line 35, in async_browse_media
channellist = await self._async_prepareChannels(hass, channel_list)
File "/config/custom_components/skyq/classes/mediabrowser.py", line 63, in _async_prepareChannels
channels = await asyncio.gather(
File "/config/custom_components/skyq/classes/mediabrowser.py", line 87, in _async_get_channelInfo
programme = await hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.8/site-packages/pyskyqremote/skyq_remote.py", line 223, in getProgrammeFromEpg
sidint = int(sid)
ValueError: invalid literal for int() with base 10: 'M217c-107-2c7-ffff'
```

**Comment by radeon79** [comment]
perfect I was sure you would succeed.
Il 19 gen 2021, 13:00 +0100, RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer <reply@reply.github.com>, ha scritto:
>
> As an fyi I have got a fix in progress for this error. Just waiting to bottom out this other problem of name resolution.

**Comment by RogerSelwyn** [comment]
Note that this is not a resolution for your name resolution issue, you will need to handle that yourself.

**Comment by radeon79** [comment]
Hello i not have any error today...probably was a problem for a epg for
previous day only.....Very thanks for your patience. Please close my ticket.


Il giorno mar 19 gen 2021 alle ore 22:34 RogerSelwyn <
notifications@github.com> ha scritto:

**Comment by RogerSelwyn** [comment]
Error shown in second post fixed with this release - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.4.12
