### ISSUE TITLE
[BUG] Device failed to connect

### ISSUE THREAD

**Issue by milobt** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#42]
**Describe the bug**  
I have three Sky Q boxes and all three were linked and working until a recent update and now none of them connect.
I tried deleting one of the boxes and readding - through the integration manager - and get a "Failed to connect, invalid host" message.
It's definitely the correct IP address and it loads a for while before displaying the message, whereas, display the message promptly when an incorrect IP address.
I tried downgrading, but can only go to v2.4.9, but still did not connect to devices.

**Screenshots**  
![image](https://user-images.githubusercontent.com/391981/107368313-4bac5f00-6ad8-11eb-84ab-f7b27fcc0642.png)
![image](https://user-images.githubusercontent.com/391981/107368398-6a125a80-6ad8-11eb-8b59-597a7330667a.png)

**Component versions**  
1. What version of SkyQ component are you using? v2.5.0
2. What was the last version where the problem was not shown? v2.4.9

**Your configuration**  
UI config

**Your configuration from the options dialogue**  
Not available as can't connect to devices.
````
**Output of HA logs**  
2021-02-09 11:17:20 WARNING (MainThread) [custom_components.skyq.media_player] W0010M - Device is not available: SkyQ Master Bedroom
2021-02-09 11:17:20 WARNING (MainThread) [custom_components.skyq.media_player] W0010M - Device is not available: SkyQ Lounge

**Comment by RogerSelwyn** [comment]
When it is failing, have you tried pinging the sky box from your HA server (via the terminal session). I think the request will timeout, but it will tell you if the name can be resolved.

Also, you can try to access `http://192.168.1.22:9006/as/system/information`, with the relevant IP. Or try `curl http://192.168.1.22:9006/as/system/information` via terminal again.

**Comment by milobt** [comment]
Sorry. Turns out it’s my router or the stupid sky boxes that don’t much like reconnecting to it.
