### ISSUE TITLE
[BUG] Pause not working with apps

### ISSUE THREAD

**Issue by smakepea** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#43]
**Describe the bug**  
When watching Netflix or Prime pausing does not work. If paused by the Sky remote pressing play does work in home assistant. Appears just pausing from home assistant is not working. 

**To Reproduce**  
1. Watching Netflix/Prime, press pause button on defult media card in HA.
2. Netflix/Prime
3. Consistently, tried many time throughout the evening
4. UK

**Expected behavior**  
Streaming video should pause. 

**Screenshots**  

**Component versions**  
1. 2.5.0 lastest stable
2. 

**Your configuration**  
UI, three boxes

**Your configuration from the options dialogue**  
program image, show live tv details, few channels select, not using switches, no custom entries 
````
**Output of HA logs**  
nothing found

**Comment by RogerSelwyn** [comment]
I've had a look at this and I fear it is some sort of problem within the SkyQ software. I can see that Pause does not work against Netflix, but does work against a standard Sky Q channel. I can also see that Play does work against Netflix. The code does not distinguish whether it is Netflix of a SkyQ channel, it just sends 'Pause' to the box in exactly the same way it sends 'Play'. So why Pause fails to work, I don't know. The SKyQ API is not published or sorted, so there is no-one to ask unfortunately.

I can't see what different command should be sent if an app is playing, I've tried 'Stop' but that didn't work.

**Comment by smakepea** [comment]
Thanks for looking into this. I tried using media_player.play_media and that works. So it would seem for apps that the play and pause functions needs to be a single play_media service call. Sure it’s possible to use an “if” within the code to determine the playing state is skyq or apps. Id attempt but my python skills are pretty bad.

**Comment by RogerSelwyn** [comment]
OK, I'll take a look, that should be possible. What parameters did you pass into play_media?

**Comment by smakepea** [comment]
So I just did a service call within HA for media_player.play_media on one of my skyq entities.

**Comment by RogerSelwyn** [comment]
play_media requires three parameters as below. Do you mean media_play?

```
entity_id: media_player.living_room_sky
media_content_id: 'record'
media_content_type: skyq
```

**Comment by smakepea** [comment]
Sorry yes media_play

**Comment by RogerSelwyn** [comment]
OK. So I need to test it, but it sounds like I need to intercept the 'pause' command and convert it to a 'play'. Strange...

**Comment by smakepea** [comment]
So I just tested the same thing on a playing skyq channel at it worked too. So maybe replace the whole media_pause command with the media_play throughout the code.

**Comment by smakepea** [comment]
I dived into the code amended the below media_pause action from self._remote.press, "pause" to self._remote.press, "play" and so far it's working perfectly on apps and skyq channels. Will let you know if i find any errors with this adjustment

async def async_media_pause(self):
        """Pause the current media item."""
        await self.hass.async_add_executor_job(self._remote.press, "play")
        self._state = STATE_PAUSED
        self.async_write_ha_state()

**Comment by RogerSelwyn** [comment]
Thanks, I'm just trialling it myself before I release. 😁

**Comment by RogerSelwyn** [comment]
Fixed with https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.1

Thanks for your help @smakepea
