### ISSUE TITLE
[Feature Request] Attributes Return Channel Numbers

### ISSUE THREAD

**Issue by smakepea** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#44]
Could the Channel Number be included in the attributes captured so that this can be used in automation's.

Example automation - Continue Watching

Capture channel playing in living room, then using this to change the channel of another box in another room for continued watching. 

Thank you

**Comment by RogerSelwyn** [comment]
Please try version 2.5.2 which is in pre-release

**Comment by smakepea** [comment]
Just installed and yes can see the channel number. This is great thank you.

**Comment by RogerSelwyn** [comment]
Closed with https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.2
