### ISSUE TITLE
Probably user error!   (new to this)

### ISSUE THREAD

**Issue by brianacox** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#46]
**Describe the bug**  
I'm trying to turn the TV (as a learning exercise) on at 9.58pm and set it to BBCEast.  I've messed about trying various things, e.g. adding select, reinstalling the latest updates, rebooting, but whilst the TV turns on at 9.58p, and the sky box also powers on, I'm let with the menu screen and the last TV station (not the one I've selected) playing in a quarter preview.  So I don't think my select source is work.  I not sure if I'm mixing YAML and UI - see below - but have also tried altering this.

Config....
 
# Sky Q
media_player:   
  - platform: skyq
    host: 192.168.0.21
    name: Bedroom SkyQ    
    generate_switches_for_channels: true
    sources:
      BBCEast: '1,0,1,select'
      BBC1HD: '1,1,5,select'
      SkyOne: '1,0,6,select'
      SkyNews: '5,0,1,select'
  - platform: skyq
    host: 192.168.0.14
    name: Lounge SkyQ   
    generate_switches_for_channels: true
    sources:
      BBCEast: '1,0,1,select'
      BBC1HD: '1,1,5,select'
      SkyOne: '1,0,6,select'
      SkyNews: '5,0,1,select'
  - platform: skyq
    host: 192.168.0.84
    name: Snug SkyQ
    generate_switches_for_channels: true
    sources:
      BBCEast: '1,0,1,select'
      BBC1HD: '1,1,5,select'
      SkyOne: '1,0,6,select'
      SkyNews: '5,0,1,select'
  - platform: skyq
    host: 192.168.0.32
    name: Log Cabin SkyQ
    generate_switches_for_channels: true
    sources:
      BBCEast: '1,0,1,select'
      BBC1HD: '1,1,5,select'
      SkyOne: '1,0,6,select'
      SkyNews: '5,0,1,select'
<img width="599" alt="Screenshot 2021-03-01 at 17 21 20" src="https://user-images.githubusercontent.com/74019941/109533860-97886d80-7ab2-11eb-8d49-0c481cd82faa.png">

<img width="1084" alt="Screenshot 2021-03-01 at 17 19 55" src="https://user-images.githubusercontent.com/74019941/109533715-7162cd80-7ab2-11eb-8783-04783f38f2ad.png">

**Comment by RogerSelwyn** [comment]
My guess is this is a race condition. What that automation will do is send a turn on command to the box and then immediately send '1,0,1,select'. It will actually space the second 1/2 a second a part, but will not do that between the turn on and the select_source sequences since that is handled by HA rather than the SkyQ integration.

I think when you say menu, you mean the bar that appears at the bottom of the screen when you press 'select'. If that is the case, I wouldn't put the select on the end. When I do run that command sequence on box that is already switched on, I get the menu bar across the bottom.

So if you were doing this yourself, would you send those command exactly like that with no breaks? I suspect you would wait for the Sky Box to switch on, then send the command. I don't use HA automations, I use Node Red, so I'm no expert in how HA does it, but you could add a 'wait for trigger' action after your turn on, or just a straight wait 5-10 seconds. Then if the select_source command works on a switched on box, it should be in the same state and work just the same.

**Comment by brianacox** [comment]
> My guess is this is a race condition. What that automation will do is send a turn on command to the box and then immediately send '1,0,1,select'. It will actually space the select_source set 1/2 a second a part, but will not do that between the turn on and the select_source sequences since that is handled by HA rather than the SkyQ integration.
> 
> I think when you say menu, you mean the bar that appears at the bottom of the screen when you press 'select'. If that is the case, I wouldn't put the select on the end. When I do run that command sequence on box that is already switched on, I get the menu bar across the bottom.
> 
> So if you were doing this yourself, would you send those command exactly like that with no breaks? I suspect you would wait for the Sky Box to switch on, then send the command. I don't use HA automations, I use Node Red, so I'm no expert in how HA does it, but you could add a 'wait for trigger' action after your turn on, or just a straight wait 5-10 seconds. Then if the select_source command works on a switched on box, it should be in the same state and work just the same.

Thanks Roger.  I've just added a delay between turning the box on and firing the sequence but this made no difference.  However, if I understand correctly, the Sources are simply predefined sequences of keys to fire at the box (as you like like pressing the buttons on the remote)?  This that's the case, when I turn on my box, I simply get - see picture below - so '1, 0, 1' won't actually do anything - (I've just tried by entering those keys) - but if I press down, right ,right ,select' then I get the channel I require, so presumably I need to define this sequence as a source (in the config file) and use this?   (or does your code fire addition keys in advance?)
![2021-03-02 17 25 52](https://user-images.githubusercontent.com/74019941/109689118-e4d11180-7b7c-11eb-9d0a-e7a8b588d172.jpg)

**Comment by RogerSelwyn** [comment]
The integration sends no extra commands, just what you enter. You could add a 'backup', before the initial '1', which I know some people do on all their sources.

**Comment by brianacox** [comment]
> The integration sends no extra commands, just what you enter. You could add a 'backup', before the initial '1', which I know some people do on all their sources, this will cancel the menu.

Well, I'm not sure what's going on... I've tried doing as you suggest in the config and directly in the interface, e.g. source: 'backup, 1, 0, 1' (I didn't know previously backup could be used as a key like this) but nothing is working... or actually doing anything.  Control over the set top box is perfect on/off every time.  I will have another look (cold light of day tomorrow) but if you get a chance please could you post your YAML example (of what you do).  I will reboot (as you suggest - not mix UI and Yaml) and try with that instead.

**Comment by RogerSelwyn** [comment]
I don't use yaml, but I'll try to put what I have in custom sources via the ui config tomorrow. You will know if your source works by testing via the standard media player Lovelace card, or via mini media player. If it works there then it will work the same via an automation.  You can equally test via developer tools/services.

**Comment by RogerSelwyn** [comment]
All the available button presses allowed are shown on the read me of this GitHub repository.

**Comment by brianacox** [comment]
Thanks... I will have a play.. I've cleaned up my HA instance now, and have sources working from Lovelace... kind of.... so I have a solid base to then try out firing various keystones (and delays) at the Sky Q boxes..... thanks Roger.

**Comment by RogerSelwyn** [comment]
Thank you Brian. Much appreciated.
