### ISSUE TITLE
[BUG] skyqchannel.yaml empty

### ISSUE THREAD

**Issue by djgragra** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#49]
![Schermata 2021-03-05 alle 10 52 38](https://user-images.githubusercontent.com/65872226/110099351-7faa3580-7da1-11eb-8366-fc6f3678565c.png)
I installed the latest sky q integration update and the switches YAML file is empty. I checked the settings and the channels are checked, the "Generate switches for channels" box but the file remains empty.
From the mediaplayer menu I can change channels.
How can I solve?

**Comment by RogerSelwyn** [comment]
Are there any errors shown in your logs? Have you rebooted your HA server? What version of the integration are you using?

**Comment by RogerSelwyn** [comment]
Also I assume you aren't looking at 'skyqchannel.yaml', but are looking for 'skyqsoggiorno.yaml' ?

**Comment by djgragra** [comment]
> Also I assume you aren't looking at 'skyqchannel.yaml', but are looking for 'skyqsoggiorno.yaml' ?

Yes my file is 'skyqSoggiorno.yaml'.
I restored the snapshot from March 4th and now everything works fine.
The version of the SkyQ integration is 2.5.3 and HACS is offering me the update to version 2.5.5.
Now I try to update again and see what happens.
![Schermata 2021-03-05 alle 11 32 31](https://user-images.githubusercontent.com/65872226/110103692-825b5980-7da6-11eb-8600-0355c97f3b99.png)

**Comment by RogerSelwyn** [comment]
You shouldn't need to restore a snapshot, if you got to reinstall SkyQ it will give an option for which version to install.

Please look in your logs for any error.

**Comment by djgragra** [comment]
Okay, I'll go back to the snapshot taken last night and then send you the log

**Comment by RogerSelwyn** [comment]
No worries, I've spotted the bug. I'll release a new version in the next hour.

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.6
