### ISSUE TITLE
Config flow fails

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#5]
Not sure if I was supposed to do anything special, but....
Removed existing yaml setup.
Restarted.
Installed new version.

New integration..
Error.....
Error occurred loading configuration flow for integration skyq: cannot import name 'CONF_CHANNEL_SOURCES' from 'custom_components.skyq.const' (/config/custom_components/skyq/const.py

After a reboot, it was more sucessful, but I’m guessing it should work without a reboot ?

**Comment by B-Hartley** [comment]
I couldn’t add the channels that I would have added in YAML, but I’m guessing that is what it is an Alpha.
Other than that, it seemed to work ok.

**Comment by RogerSelwyn** [comment]
Should it work without a reboot? I thought it might, but it seems like it doesn't re-load all component, so it looks like a fail. Normally you always need a reboot for a HACS update, so I'm not sure what HACS has done in its latest release to enable updates without a reboot.

It's an alpha release and not ready for use yet.... I have other bugs I'm dealing with, but posted to GitHub so I can test it all the way through on my home setup.

**Comment by B-Hartley** [comment]
That’s a good point.  Didn’t occur to me that it would normally ask for a reboot, but it hadn’t.
Although I did add another component for similar reasons earlier and I don’t think I had to reboot.

no problem, just thought I’d give it go.  Let me know if you need any testing later.

**Comment by RogerSelwyn** [comment]
You will find you need to add a custom source in the version you have, if you try the options. Also you will need to add at least one source item. Both items I am fixing. For custom source you can put {"Foo":"Bar"}. Which it should accept. This is the equivalent of the sources in the YAML file, which I can see some folks might wish to still be able to use the mechanism for arbitrary commands on the sources drop down.

**Comment by RogerSelwyn** [comment]
They may get fixed tonight, but definitely tomorrow.

**Comment by B-Hartley** [comment]
I’ve reverted it for now. 
Which was a challenge in itself as HACS doesn’t seem to work well at the moment. 
Out of interest what do you mean by add custom source and how would I do that ?

**Comment by B-Hartley** [comment]
Oh. Just thought. You mean from the integration screen. On the config dialogue.

**Comment by RogerSelwyn** [comment]
The sources your would normally put in your yaml file which are not just standard channels (you can select them in the channel sources at the top of the option screens), you can put in the custom sources at the bottom of the options screen. {“Netflix”:”home,down,....”,”Foo”:”command,...”}.

**Comment by B-Hartley** [comment]
Sounds good. Thanks. 
Will wait for it to get to beta at least. Can’t afford to break it too much as it’s our main lounge remote control.

**Comment by RogerSelwyn** [comment]
Should be fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.2.0.alpha2

**Comment by B-Hartley** [comment]
Thanks. Will try tomorrow.

**Comment by B-Hartley** [comment]
Installed latest. 
Can’t get custom sources to work ?

I put in:

{“BBC1”,”1”}

As I have it in favourite channels. 

Thinking about it it might respond quicker for 101 than to 1. Will have to test. 
anyway it won’t accept the json. 
What have I done wrong ?

Thanks.

**Comment by RogerSelwyn** [comment]
That isn’t quite Json 😀. The comma should be a semi-colon.

**Comment by RogerSelwyn** [comment]
But you can just select that in the channel sources at the top of the options dialogue. No need to put in the custom sources at the bottom, but it will use 101 or 115 for the HD channel.

**Comment by B-Hartley** [comment]
doh ! Thanks.  I normally have it call channel 1 for BBC1 HD, 2 for BBC2 HD etc. with them set up as favourite channels, not sure if it is any quicker than the full channel number when sending through network, but anyway, like to test everything !

All ok now.
I have latest Alpha installed on SkyQ and 2 minis and all seems good !

**Comment by RogerSelwyn** [comment]
Let me know how it goes.

**Comment by RogerSelwyn** [comment]
I've posted a beta 1, because I think it is now at a level of code stability to warrant it, let me know how it goes.

**Comment by B-Hartley** [comment]
Ok, thanks.  I’ll see how it goes.

**Comment by RogerSelwyn** [comment]
Fixed by - [v2.2.0](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.2.0)
