### ISSUE TITLE
[Feature Request] Additional Attributes - Recording State

### ISSUE THREAD

**Issue by smakepea** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#50]
**Is your feature request related to a problem? Please describe.**  
Is it possible to see an attribute if the current channel is being recorded. Option could be that the media_type could switch from live to pvr

**Describe the solution you'd like**  
If watching a live channel and you have selected record, can an attribute display this. Currently if you enable recording whilst watching a live channel, the media_type remains live and does not changed to pvr. 

**Describe alternatives you've considered**  
Don't currently have a workaround for this. 

**Additional context**  
I have an automation whereby I can walk into the kitchen and continue watching the content from the living room. I do some analysis to understand what it was in the living room and therefore do the following in the kitchen
if living room media_type = live and previous state was not paused, then kitchen change channel
if living room media_type = live and previous state was paused, then living room pause, record, kitchen navigate to most recent recording.
if living room media_type = pvr then living room pause, kitchen navigate to most recent recording.
if living room media_type = apps then living room identify app, kitchen navigate to app.

The current issue I face is that if i was recording the channel in the living room and want to continue in the kitchen I can't tell if it currently being recorded or not. therefore when it attempt to continue in the kitchen based on the above parameters it will either change channel (meaning i continue watching from a possible different point then if i had paused and recorded in the living room) or it could cancel the recording which and not continue correctly. 

I have the workaround above that if it sees that the previous state was paused, it safe to assume i paused something whilst watching and would want to continue from that point in the next room, so enabling recording works. But what if in the same instance of watching i have paused, recorded, continued to watch and then paused again. the above routine would cancel the recording. 

I hope the below makes sense. Please let me know if i can explain anything any further. 

thanks again for all the work you have done on this.

**Comment by RogerSelwyn** [comment]
Sorry, not this not visible via the api.

**Comment by smakepea** [comment]
Thanks for checking. I created a workaround using this API to get the list of recordings, filter out current channel and then check the status for recording. 
http://<skyboxip>:9006/as/pvr?limit=1000&offset=0

**Comment by RogerSelwyn** [comment]
Hi, interesting idea and thanks for highlighting a way of doing it. I think this is a little over the top for what the integration needs to do. Some people have reported issues with the integration crashing their sky box (I think it has happened to me once), so I try to keep calls to a minimum especially to port 9006. Sorry, I was busy earlier, so apologies for the very brief, grammatically incorrect reply 😞

**Comment by smakepea** [comment]
Oh yeah it’s completely over the top lol. I’m just trying to replicate sky’s continue watching functionality really. I’m regards to crashes, yes once or twice I’ve had distorted pictures but so far everything has been okay, and that’s with three Sky boxes too. Very happy with the current interrelation.

**Comment by RogerSelwyn** [comment]
Try version 2.5.7 and look for `liverecord`.

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.7

**Comment by smakepea** [comment]
Oh wow you added it? Is this polling amongst the other data? Just for reference in my workaround I was only pulling for that particular functions in my node red automation. I’ll give this a go later today and see if there are any issues.

**Comment by RogerSelwyn** [comment]
I added an extra query to get the data from that URL. If causes problems, I may then add an option to enable it.

**Comment by smakepea** [comment]
So far so good. Have noticed one possible glitch whereby  I was navigating to apps on one box and there were no thumbnails for the apps. Will keep an eye on it. I also have polling on one box at every 2 secs so I may be straining it more

**Comment by RogerSelwyn** [comment]
Thumbnails would be different to any code I changed here, unless there is something obscure I missed.

**Comment by smakepea** [comment]
So this was thumbnails in the sky menu. So I’m thinking maybe the persistent data pulls was affecting the loading of data or something. At this point all 3 boxes were on, not sure if that makes a difference. If honest I have no clue what I’m talking about lol, just looking for behaviour different to prior to having the integration

**Comment by RogerSelwyn** [comment]
To be honest I have no idea. The problem is there is no formal skyq api, it is all discovered by people looking at traffic. So it isn't really clear if there are any impacts of querying the box.

**Comment by RogerSelwyn** [comment]
Closed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.7

**Comment by RogerSelwyn** [comment]
@smakepea - when you install v2.5.8, you will need to enable the relevant set "Get Live Record Status", in the options. It seems the extra calls to the box are causing errors as I indicated they might, so I've set the default to off.

**Comment by smakepea** [comment]
Thanks for the heads up. I’ve not had any issue which is great, but yes suspected the extra calls would impact somewhere.
