### ISSUE TITLE
[BUG] Q STB lock-up

### ISSUE THREAD

**Issue by gee-jay-bee** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#51]
**Describe the bug**  
I have been using this custom component for quite some time now and have experienced no stability issues until the 2.5.7 release. Since updating, the STB becomes unresponsive after some time and is recoverable only by power-cycling. 

**To Reproduce**  

The issue occurs arbitrarily with 2.5.7. I'm in GBR.

**Expected behavior**  
STB is always usable

**Screenshots**  
N/A

**Component versions**  
1. What version of SkyQ component are you using?
2. What was the last version where the problem was not shown?
2.5.7 seems to have introduced the issue, earlier strains of 2.5.x didn't. I have now rolled back via HACs to 2.5.6 and so far so good but as the issue occurs arbitrarily, only time will tell!

**Your configuration**  
UI config flow, installed via HACs.

**Additional context**  
The component itself seems to be behaving itself. It simply sees that the STB is unavailable.

**Comment by RogerSelwyn** [comment]
OK, I suspect this is related to the increased number of calls made to the STB in 2.5.7. I'll add an option over the next few days to default them off. Expect to see a new version sometime over the week-end.

**Comment by RogerSelwyn** [comment]
Closed with https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.8

**Comment by gee-jay-bee** [comment]
Run for over a week now without seeing issues so seems to have done the trick

**Comment by RogerSelwyn** [comment]
Good to hear
