### ISSUE TITLE
generate_switches_for_channels problem - the file skyq<room>.yaml in the /config path created empty

### ISSUE THREAD

**Issue by micium** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#54]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.helpers.entity
Source: custom_components/skyq/classes/switchmaker.py:48
Integration: Sky Q (documentation, issues)
First occurred: 00:44:54 (1 occurrences)
Last logged: 00:44:54

Update for media_player.skyq fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/config/custom_components/skyq/media_player.py", line 362, in async_update
    Switch_Maker(
  File "/config/custom_components/skyq/classes/switchmaker.py", line 34, in __init__
    self._addSwitch("pause", "pause", "media_pause")
  File "/config/custom_components/skyq/classes/switchmaker.py", line 48, in _addSwitch
    if len(self._alias) > 0:
TypeError: object of type 'NoneType' has no len()

**Comment by RogerSelwyn** [comment]
Please provide details of the version you are using as well as a copy of your yaml configuration or screenshots of gui.

**Comment by micium** [comment]
I Roger, In attached files the screenshots of GUI and integration version.

thanks in advance
Massimo
![UI integration](https://user-images.githubusercontent.com/62593595/117566793-fffa5900-b0b8-11eb-9665-3e2b5af3f3c7.jpg)
![version](https://user-images.githubusercontent.com/62593595/117566797-04267680-b0b9-11eb-8a9e-3395c788480e.jpg)

**Comment by RogerSelwyn** [comment]
Ok, I’ll take a look when I get home next weekend

**Comment by RogerSelwyn** [comment]
I believe this is caused by you have an empty alias file. In theory you should have a file with some aliases in, or no file at all. I'll adapt the code to handle this situation.

**Comment by RogerSelwyn** [comment]
Closed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.6.0
