### ISSUE TITLE
Additional EPG for non Sky Channel

### ISSUE THREAD

**Issue by bluenazgul** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#55]
would it be somehow possible to integrate this XML EPG https://xmltv.xmltv.se/00index.html for additional non Sky Channel?

**Comment by RogerSelwyn** [comment]
Many things are possible :-).  If you can think of a way to reliably link from the available key data (channel id, number, name) to this, I can try what can be achieved. But I don't see that linkage at present.

**Comment by bluenazgul** [comment]
Iam not the Developer 😅 but my idea is an Option to add an Ui or config file for Custom EPG by channel

**Comment by RogerSelwyn** [comment]
Can you pick a channel where you think this would add info, and I'll have a think on it. Could potentially add a lookup file to tie channel id to xml.

**Comment by bluenazgul** [comment]
I would test it with "RTL Television" (SD is 183 and HD is 163) in Germany.

The XML for today would be http://xmltv.xmltv.se/hd.rtl.de_2021-05-27.xml

SD and HD Channel uses the Same EPG

So there must be a date checker too, coz every day the URL changes date specific

**Comment by bluenazgul** [comment]
![Screenshot_20220517_234709_de sky bw](https://user-images.githubusercontent.com/171537/168915924-04d93e98-29bf-4abd-bc5a-c6d1cbe69628.jpg)

I just checked the German SkyQ App again, there must be a Source to get the EPG for non Sky Channels, but Until now iam unable to locate an url, but maybe it's a hint

**Comment by RogerSelwyn** [comment]
If you know how to use a network sniffer/packet catcher tool, you can capture the traffic from the Sky Go app on Windows or Android to see where it is getting it from.

**Comment by bluenazgul** [comment]
![Screenshot_20220518_002827_com minhui networkcapture](https://user-images.githubusercontent.com/171537/168922613-6b4c8b1a-31ce-4eac-98cc-5edd5c368391.jpg)

All i could find is something about 

atlantis.epgsky.com

But iam not allowed to access that side

**Comment by RogerSelwyn** [comment]
I personally use fiddler on Windows, which will decrypt the traffic, so you can see all the calls and returns.  UK uses Atlantis so it maybe they are now to a common standard. I'll try and take a look over the next few days.

**Comment by RogerSelwyn** [comment]
The Atlantis URL does work for getting the schedule back, but with the information it provides I can't figure out the correct image url. It should be something like - https://imageservice.sky.com/...... but for Germany of course it could be something different.

**Comment by bluenazgul** [comment]
According to fast capture for Germany it seems to be "de.imageservice.sky.com"

![Screenshot_20220518_100746_com minhui networkcapture](https://user-images.githubusercontent.com/171537/168990099-9687dfab-b3a4-4c19-9904-6b31335d0b9e.jpg)

**Comment by RogerSelwyn** [comment]
In your SkyQ manifest.json try changing pyskyqremote to 0.3.8

**Comment by bluenazgul** [comment]
Changed it, will test this after, right now SkyQ is in deepsleep Mode, so I can only Start using the remote and unable to controll it using HA (Safes about 30W)

**Comment by RogerSelwyn** [comment]
As an fyi, this also works for Italy, so I should be able to significantly reduce the complexity of code since all countries are now using the same method for schedule and image handling.

**Comment by bluenazgul** [comment]
now the integration wont load here

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/skyq/config_flow.py:140
Integration: Sky Q (documentation, issues)
First occurred: 16:23:22 (1 occurrences)
Last logged: 16:23:22

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 243, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/skyq/config_flow.py", line 140, in async_step_init
    self._remote = self.hass.data[DOMAIN][self._config_entry.entry_id][SKYQREMOTE]
KeyError: '7fcbae4d035e11ebbf31330c9796ec6f'

**Comment by RogerSelwyn** [comment]
Where you on latest version? If not just reinstall whatever you had before.

**Comment by RogerSelwyn** [comment]
Also, this seems strange because it shouldn't pass through that code at startup. That is only executed when you click Configure on the Sky Q card of the Integrations tab.

**Comment by RogerSelwyn** [comment]
So all working fine?

**Comment by bluenazgul** [comment]
Right now I cant find any issues

**Comment by bluenazgul** [comment]
![image](https://user-images.githubusercontent.com/171537/169089124-2300bd50-f1b5-4f74-a597-83f43f06f7ea.png)

My SkyQ Pannel is looking great now while running an non Sky Channel

**Comment by RogerSelwyn** [comment]
I’ll look to release a new version which will work for Italy as well then, as a full SkyQ release.

**Comment by RogerSelwyn** [comment]
It was simple when I had the right info, since I already had GBR setup that way ;-) I've also removed all the complex code to handle the different ways of getting the info. Much cleaner.

**Comment by RogerSelwyn** [comment]
Feature added by code improvement to standardise EPG retrieval from common source across countries - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.9.1
