### ISSUE TITLE
using Mediabrowser or DropDown to open Netflix, Disney+ and Co

### ISSUE THREAD

**Issue by bluenazgul** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#57]
iam getting crazy to get Netflix and Co shown in Lovelace, could you please point me to where and how to add them?

**Comment by RogerSelwyn** [comment]
I’m away on holiday so I can’t help now, but if you can expand on what the particular problem is that would help. Also provide details of your configuration. 

Have you looked at the custom Source configuration on the read me on this GitHub?

**Comment by RogerSelwyn** [comment]
If you look at this section it shows the structure of the custom source configuration. They section below on buttons shows what buttons you can use, essentially those that are available on the Sky remote.

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#sources

**Comment by RogerSelwyn** [comment]
From somebody else's post von the forum you will need something like the following. I haven't validated they key presses.

{“Netflix”: “home,down,down,down,down,down,down,down,down,down,down,right,select,select”, "Second": "button, button,..."}

**Comment by RogerSelwyn** [comment]
No further information around this request supplied, so closing.
