### ISSUE TITLE
[BUG] ios remote doesnt pass volume commands to amp

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#66]
**Describe the bug**  
iOS remote control doesn't pass volume commands to volume entity. 

Should this work. 
Volume
Within a media player is passed to my amp correctly. 
But from the iOS HomeKit remote it doesn't work ?

Latest component Varsion and home assistant version. 
If it is Supposed to work, what would you like to know to debug. 

Thanks.

**Comment by RogerSelwyn** [comment]
Final release of this version - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.6.10
