### ISSUE TITLE
Mini media player card setup

### ISSUE THREAD

**Issue by icornish72** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#68]
I have got skyq setup and it's ok with the default media player. But I like the look of the example using mini media player, so have installed that. But I can't get all the buttons working and can't get the background to show the current program.
Can the config of mini media player be shared to help us make the most of it?

**Comment by RogerSelwyn** [comment]
You should find various versions in this thread - https://community.home-assistant.io/t/custom-component-skyq-media-player/140306. I think post 444 shows my setup.

**Comment by RogerSelwyn** [comment]
No further info requested.
