### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Danyasr** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#76]
good evening. I have a problem I can't get the channel change to work with google home. i used the built-in function of creating switches but then i didn't understand how to integrate it with google. the sky q is integrated and I can turn it off and on, to see the status (on off) but I can only change the channel via the home assistant. can you help me please? thank you

**Comment by RogerSelwyn** [comment]
It would be best if you ask that question in the HA forum - https://community.home-assistant.io/t/custom-component-skyq-media-player/140306/810. 


I don’t use Google Home so don’t have knowledge on how to help you.
