### ISSUE TITLE
Media player does not showed paused when programme is paused

### ISSUE THREAD

**Issue by lorenzo1773** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#81]
**Describe the bug**  
After the click on the mediaplayer pause button, the associated SkyQ goes to paused status but the mediaplayer goes to puased status only just a moment and the mediaplayer state, discovered for instance using the developers tools, is playing despite SkyQ is puased-

**To Reproduce**  
1. Start playing what you want on your SkyQ
2. Click on pause command

**Expected behavior**  
SkyQ goes to paused status and the related maediaplayer stay on pause until the click on play button

**Component versions**  
1. the problem is present in 2.7.4, 2.7.5, 2.7.6
2. the problem is not present in 2.6.10

**Your configuration**  
by UI
![image](https://user-images.githubusercontent.com/68913455/146072489-0a5ab6c5-cc20-43d8-979f-eeadb85ac05f.png)

**Comment by RogerSelwyn** [comment]
I will release a new version of the integration after running it overnight. If you would like to test it sooner, update the version of pyskyqremote in manifest.json to 0.2.54.

**Comment by lorenzo1773** [comment]
v 2.7.6 fix the bug! thanks!
