### ISSUE TITLE
[Feature Request] Add AppleTV+ Logo

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#83]
Add SkyQ logo for AppleTV+

AppleTV+ is now a live app on SkyQ.

**Comment by RogerSelwyn** [comment]
Added - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.7.8

**Comment by B-Hartley** [comment]
Thanks, sorry about the dodgy subject, created it on my phone and couldn't seem to edit it.

**Comment by RogerSelwyn** [comment]
No worries 😀
