### ISSUE TITLE
[BUG] media_player getting renamed unexpectedly

### ISSUE THREAD

**Issue by mark007** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#86]
**Describe the bug**  
I have two skyq boxes, one which showed up as media_player.living_room_sky. I have many automations and scripts tied to this name. Yesterday I noticed it had changed name to media_player.living_room_sky_3 (A media_player.living_room_sky_2 had shown up a few weeks ago and I guess still lingers there, unavailable).

I tried to rename the entity back to the originalname, to save me having to update lots of automations/scripts, but when I click edit on the media_player.living_room_sky_3 entity to try to edit itsname, it shows this. It looks to me like it doesn't have a unique ID and if it did, it might solve this issue (as other integrations I have like LIFX seemed to suffer the same issue until they had a robust unique ID in place like the mac address).

`This entity ('media_player.living_room_sky_3') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.`

Is there a way to ensure that any HA update/SkyQ integration update / HA restart, can never rename a media player like this?

**To Reproduce**  
1. What were you doing/watching at the time ? I am not exactly sure what triggered it, or if it was after a HA restart, HA update, SkyQ integration update, all of which happened in recent days.
2. What channel were you on? NA
3. What time did the problem occur? I only noticed it yesterday but it seems the old entity name was 'Unavailable' for some time before that, possibly a day or two.
4. Where are you (bear in mind component supports GBR/ITA at the moment)? IRE

**Expected behavior**  

**Screenshots**  
na

**Component versions**  
1. What version of SkyQ component are you using? v2.7.9
2. What was the last version where the problem was not shown? It was fine on v2.7.9 as far as I am aware, for a few days but I can't  be 100% sure when the rename occurred or what triggered it.

**Your configuration**  
How have you setup your devices, by UI or YAML? YAML

**Your configuration from the options dialogue**  
or  
**Your configuration.yaml**  
This is how this one looks in my configuration.yaml

```yaml
media_player:
 - platform: skyq
   name: Living Room Sky
   host: 192.168.86.23
   sources:
     RTÉ One HD: '1,0,1'
     RTÉ2 HD: '1,0,2'
     Virgin One HD: '1,0,3'
.
.
```
**Output of HA logs**  
I can provide whatever logs are required, but not sure what I should include here as of yet.

**Additional context**

**Comment by RogerSelwyn** [comment]
Please upgrade to 2.7.10 and confirm if this fixes the issue.

**Comment by mark007** [comment]
Yes, it looks to have fixed it, the media player name immediately reverted back to living_room_sky instead of living_room_sky_3 and it can be edited (no longer says it doesn't have a unique ID). Thanks so much! Quickest fix in history! Happy new year!

**Comment by RogerSelwyn** [comment]
No problem 😌
