### ISSUE TITLE
Which button is text?

### ISSUE THREAD

**Issue by Stexjy** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#87]
Hello so I was wondering what the button text does

**Comment by RogerSelwyn** [comment]
To be honest I don't know? It is listed on many other implementations as being an available button, and was in the code when I took it on. I'd suggest trying it and seeing what happens. In theory it should map to a physical button on the remote. If you are interested, it says '15' to the sky box as listed here - https://github.com/RogerSelwyn/skyq_remote/blob/master/pyskyqremote/const.py

**Comment by Stexjy** [comment]
I tried it and it didn't seem to do anything, I'll try again when I'm back from vacation

**Comment by RogerSelwyn** [comment]
No further information provided
