### ISSUE TITLE
Issue on channel list in config flow

### ISSUE THREAD

**Issue by ollo69** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#9]
**Describe the bug**  
First of all thanks for great job with this component.

Just two little bug that I found in the channel list generation from config flow:

1. if I go to the integration options and I add a new channel to the existing list, the list is duplicated and report a double list, the first with the original list and the second with the original plus the new channel (see screnshot)
2. rebooting HA, point 1. is fixed but the channel list defined on my first SkyQ  is duplicated on the second SkyQ Mini

**Screenshots** 

![image](https://user-images.githubusercontent.com/60491700/83548536-36704100-a504-11ea-9b40-3e54920d83ff.png)
 

**Component versions**  
1. What version of SkyQ component are you using? v2.2.0
2. What was the last version where the problem was not shown? v2.2.0

**Your configuration**  
How have you setup your devices, by UI or YAML?

UI

**Your configuration from the options dialogue**  

Main Sky Q config
![image](https://user-images.githubusercontent.com/60491700/83549071-04131380-a505-11ea-8cf9-00d127734447.png)

Sky Q Mini config

![image](https://user-images.githubusercontent.com/60491700/83549341-7683f380-a505-11ea-946a-5e9ce9ec41e4.png)

**Comment by RogerSelwyn** [comment]
Thanks for reporting. Should be fixed by [v2.2.1](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.2.1
)
