### ISSUE TITLE
Can't make a call to change channel using three digit channel number.

### ISSUE THREAD

**Issue by gpchampion** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#90]
Using this via node Red and I cannot get the call to change the channel by number. It will change single numbers e.g. 1-9, but nothing greater. Example call is below extracted from NR debug log attempting change of channel to 501 Sky News.. The call is accepted into the API via this function:

msg.channel = {"media_content_id": ""+ msg.payload.new.slice(0, -1) +"","media_content_type":"skyq"}

The above is then passed into the service call as an expression.

19/01/2022, 10:36:44node: Set Lounge Sky channel
msg :
object
domain: "media_player"
service: "play_media"
data: object
media_content_id: "5,0,1"
media_content_type: "skyq"
entity_id: "media_player.sky_q_living_room"

I have tried this manually using "501" "5,0,1" via HA developer tools and cannot get it to work.

Using HA 2021.12.9 HA OS

SkyQ V2.7.10

**Comment by RogerSelwyn** [comment]
Interesting one because you are right it only supports single buttons. I'll release a new version shortly that supports media_id in the format of `command, command,command,command,...`

**Comment by gpchampion** [comment]
Many Thanks for the swift response Roger. Its a great addon to HA, so thanks for the continued works as I for one appreciate the amount of time and effort these things take up :)

**Comment by RogerSelwyn** [comment]
Closed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.7.12

**Comment by RogerSelwyn** [comment]
> Many Thanks for the swift response Roger. Its a great addon to HA, so thanks for the continued works as I for one appreciate the amount of time and effort these things take up :)

Fortunately it is mostly ticker these days unless some new feature comes out like Media Browser. But I like to keep on top of things, so usually handle it pretty quick if I can.

**Comment by gpchampion** [comment]
Retested the change. All working fine. I use it via Alexa and NR to utter the channel number changes and its working spiffingly! So remote control free on Sky Q. Speak the channel change number to Alexa and off She goes :)

I've also got it working in theory using Alexa voice and fuzzy matching of the spoken channel names via virtual Alexa in NR, but its very hit and miss as to whether it gets the channel names correct, plus it messes with case sensitivities when matching unfortunately. But for the purposes of this addon topic all is good. Many thanks.
