### ISSUE TITLE
[Feature Request] Ability to see if user is within the TV guide

### ISSUE THREAD

**Issue by mark007** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#97]
**Is your feature request related to a problem? Please describe.**  
I have an automation set up that works well that watches if the media channel is set to a non HD channel for more than 5 seconds. If so it switches channel to the HD version. However if the user has selected the channel from within the TV guide and is browsing channels, this can be disruptive as they may be visually looking down through channels when the three numbers of the HD channel get typed in.

**Describe the solution you'd like**  
I would request a way to know if the user is within some sky menu / TV guide. If so I break out of the automation and only if they were on a non HD channel AND not in a menu browsing around, I would change the channel.

**Describe alternatives you've considered**  
I have not yet figured out a better way to decide whether to run the automation or not unless I can detect via keypresses on the sky remote whether they are browsing a menu.

**Additional context**  
NA

**Comment by RogerSelwyn** [comment]
I'm afraid it is not possible to detect whether the Sky Q box is on the menu or not (or at least if it is, I don't know how). Equally, it isn't possible to track what buttons are pushed on the physical remote. Whilst it might be possible to track buttons on the virtual remote with HA, I would suggest there are likely to be better ways of presenting options to the user to encourage use of HD channels.

**Comment by mark007** [comment]
No problems thanks very much for the speedy reply
