### ISSUE TITLE
[BUG] Config flow error not displaying / mDNS not working

### ISSUE THREAD

**Issue by SparkyDan555** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#98]
**Describe the bug**  
Attempting to add Sky Q box via mDNS hostname gives an error but does not show the error. Adding boxes this way used to work correctly.

**To Reproduce**  
1. Install add on through HACS
2. Add sky q box via mDNS hostname i.e. skyq.local

**Expected behaviour**  
Config flow shows succeeds and the box is added using hostname.

**Screenshots**  
<img width="660" alt="Screenshot 2022-04-14 at 7 18 28 pm" src="https://user-images.githubusercontent.com/38540799/163452433-1bca40d9-1d97-41e0-b777-15e36ae60cf7.png">

**Component versions**  
1. What version of SkyQ component are you using? 2.8.9
4. What was the last version where the problem was not shown? Unknown

**Your configuration**  
How have you setup your devices, by UI or YAML? UI

**Your configuration from the options dialogue**  
<img width="660" alt="Screenshot 2022-04-14 at 7 22 19 pm" src="https://user-images.githubusercontent.com/38540799/163453068-19f6a378-2cbc-42d4-925d-d30a1dfc25fc.png">

**Output of HA logs**  
Nothing relevant

**Comment by RogerSelwyn** [comment]
Have you validated that the name resolved via a terminal session on your HA server?

**Comment by RogerSelwyn** [comment]
By the way there does seem to be a spurious blank 'error' line when it can't resolve the name, but I don't believe that should be there, it does say it failed to connect, so I don't believe the name is resolving.

**Comment by RogerSelwyn** [comment]
If no further information provided, this will be closed in the next few days.

**Comment by RogerSelwyn** [comment]
Assuming you have SSH & terminal add-on installed:

- Go into terminal session and type `nslookup skyq.local`

You should get a response like the below
<img width="400" alt="Screenshot 2022-04-25 at 10 30 39" src="https://user-images.githubusercontent.com/7115783/165061883-e5d97df6-5ad2-4d0e-97c7-c84fc52e4c5d.png">

**Comment by SparkyDan555** [comment]
Hmm, I just get `server can't find skyq.local: NXDOMAIN` even when I try from my PC. I have checked my router and it just shows the sky boxes IP address, no hostname. It seems the sky q box is not sending its hostname alongside the DHCP request?

**Comment by RogerSelwyn** [comment]
You may be able to set the name on the router, depends what you have. Personally I have an Asus router which I added the name to test this out. If it can’t resolve then the best way to do it is to use the IP address.

**Comment by SparkyDan555** [comment]
I have an OpenWRT system so I have made an entry under static leases with suitable hostnames for each box. Putting this into the config flow works with no problem. The blank error line only seems to appear with mDNS hostnames. Closing since this is likely not a problem with this integration and depends on whether mDNS is working on a specific box.

**Comment by RogerSelwyn** [comment]
I have added a fix for the blank error in the next release.
